import type { AILessonConfig } from "@/components/ai/AILessonCanvas";

const check = (prompt: string, choices: string[], correctIndex: number, explanation: string) => ({ prompt, choices, correctIndex, explanation });

export const digitalLesson2: AILessonConfig = {
  id: "dl-2", title: "2. Data Storage Tradeoffs: Local, Cloud & Organization",
  goal: "Evaluate tradeoffs—cost, speed, reliability, accessibility, privacy, and integrity—for where and how data is stored and organized.",
  xpReward: 100, badge: "Storage Strategist", dashboardHref: "/dashboard", prevHref: "/learn/digital/1", nextHref: "/learn/digital/3",
  lessonModule: { durationLabel: "~25 min lesson", sections: [
    { id: "start", kicker: "Start here", title: "Storage is a decision, not a default", body: `A scholarship essay, group-project video, and first-job résumé do not all need the same storage plan. Where data lives affects who can reach it, how quickly it opens, what it costs, and how recoverable it is.\n\nYour job is to evaluate those tradeoffs and recommend a plan for the stakes of the task.`, image: "/images/lessons/dl-2.png", imageAlt: "Files organized across a laptop and cloud storage" },
    { id: "data", kicker: "Core concept", title: "Files are data with structure", body: `A file stores data; a folder or directory organizes files; a path identifies where a file is located. Names, folders, and formats are not cosmetic. They affect whether a teammate can find the correct version and whether a portal can use it.\n\nUse a clear project structure: \`Applications/State-U/essay-2026-04.pdf\`, not a Downloads folder full of “final-final.”` },
    { id: "local", kicker: "Option 1", title: "Local storage: fast and direct", body: `**Local storage** keeps data on a device you control. It can be fast and available without internet access. It may also be inaccessible if the device is lost, damaged, uncharged, or unavailable.\n\nLocal storage is useful for large media files, offline travel, and sensitive work—but it is not automatically reliable without a separate backup.`, checkIn: check("Which is a major advantage of local storage for a student editing video on a bus?", ["It is always shared with teammates” belongs to a different situation than the one in the question stem", "It can remain available without an internet connection", "It has no privacy risk” belongs to a different situation than the one in the question stem", "It automatically creates a backup” belongs to a different situation than the one in the question stem"], 1, "Local files can be available offline; that convenience does not guarantee sharing or recovery.") },
    { id: "cloud", kicker: "Option 2", title: "Cloud storage: accessible, with dependencies", body: `**Cloud storage** keeps data on a provider’s remote systems and typically lets authorized people reach it from multiple devices. It supports collaboration, version history, and recovery from one lost device.\n\nIts tradeoffs include account access, network dependence, subscription limits, provider policies, and possible privacy concerns. “Cloud” does not mean cost-free, private by default, or immune to mistakes.`, image: "/images/lessons/dl-2-2.png", imageAlt: "Devices accessing shared cloud files" },
    { id: "compare", kicker: "Compare", title: "Evaluate six storage criteria", body: `Use a consistent lens: **cost** (price and time), **speed** (opening and transfer), **reliability** (failure and recovery), **accessibility** (where and for whom it works), **privacy** (who can view it), and **integrity** (whether it stays accurate and complete).`, table: { columns: ["Criterion", "Local storage", "Cloud storage"], values: [["Speed", "Often fast on the device", "Depends on connection and sync"], ["Accessibility", "Usually one device", "Authorized devices and collaborators"], ["Reliability", "Risk if one device fails", "Risk from account/service/sync failures"], ["Privacy", "More direct physical control", "Depends on permissions and provider"]], rowCount: 4 }, checkIn: check("A group needs to edit one shared presentation from school and home. Which criterion most strongly favors cloud storage?", ["Accessibility for authorized collaborators", "No cost” belongs to a different situation than the one in the question stem", "No need for permissions” belongs to a different situation than the one in the question stem", "Guaranteed privacy” belongs to a different situation than the one in the question stem"], 0, "Shared cloud storage can make the current file reachable to authorized collaborators from more locations.") },
    { id: "integrity", kicker: "Integrity", title: "Organization protects the right version", body: `Data integrity means data remains accurate, complete, and usable. A chaotic folder can create an integrity problem when a team submits an outdated draft or overwrites the approved version.\n\nUse meaningful names, shared conventions, limited edit permissions, and version history. Do not rename a file extension to “convert” it; export from the application so the data actually matches the required format.` },
    { id: "sync", kicker: "Important distinction", title: "Sync is not a backup", body: `**Sync** keeps locations matched. That includes deletions and corrupted edits. A **backup** is a separate recoverable copy. Version history can help, but its retention period and recovery rules vary.\n\nFor high-stakes work, use more than one independent copy and test that recovery works.`, checkIn: check("Why can a synced folder fail as the only backup for an internship portfolio?", ["An accidental deletion or bad edit can propagate to every synced location", "Backups must be printed” belongs to a different situation than the one in the question stem", "Cloud files cannot be opened” belongs to a different situation than the one in the question stem", "Sync always prevents deletion” belongs to a different situation than the one in the question stem"], 0, "Sync mirrors changes; a separate backup is designed to survive them.") },
    { id: "privacy", kicker: "Privacy", title: "Access is part of storage design", body: `A shared link is a storage decision because it determines who can read, comment, or edit. “Anyone with the link can edit” may be convenient for a club flyer and unacceptable for a résumé list containing contact information.\n\nUse the least access needed: view, comment, or edit. Review sharing before sending a link.` },
    { id: "cost", kicker: "Cost", title: "Free can still have a price", body: `A free service may limit storage, show ads, collect usage data, or make export harder later. A fast local drive costs money and can fail. Your time is also a cost: disorganized files create deadline risk.\n\nEvaluate total cost, not just the price shown today.` },
    { id: "case", kicker: "Case study", title: "A scholarship application packet", body: `A student needs a private draft, a PDF upload, feedback from a counselor, and a safe copy before the deadline. A strong plan might use a private cloud folder with counselor comment access, a clearly named PDF export, version history, and an independent backup.\n\nThe recommendation works because it connects each choice to a need: collaboration, format, privacy, integrity, and recovery.`, image: "/images/lessons/dl-2-3.png", imageAlt: "Application documents with version history" },
    { id: "recommend", kicker: "Recommendation", title: "Match the plan to the risk", body: `For a temporary class handout, a simple shared link may be enough. For a group research dataset, use clear roles and a documented source of truth. For tax, medical, or identity documents, minimize sharing, use strong account security, and maintain independent backups.\n\nThere is no universal “best” location. There is a defensible plan for a particular purpose.`, checkIn: check("Which plan best protects privacy and integrity for a résumé containing personal contact details?", ["Private folder, limited sharing, clear version names, and a separate backup", "Only one unnamed file in Downloads” belongs to a different situation than the one in the question stem", "Public edit link so anyone can help” belongs to a different situation than the one in the question stem", "Post it in a group chat” belongs to a different situation than the one in the question stem"], 0, "The plan limits unnecessary access while making the correct version recoverable.") },
    { id: "practice", kicker: "Decision routine", title: "Ask six questions before you save", body: `Who needs access? How quickly must it open? Can work continue offline? What is the cost? What happens if the device, account, or service fails? How will you confirm the correct version is used?\n\nAnswering these questions is more useful than automatically choosing local or cloud storage.` },
    { id: "impact", kicker: "Impact", title: "Storage choices shape opportunity", body: `A student without reliable home internet experiences cloud-only assignments differently from a student with constant access. A school or employer also has responsibilities when required tools create cost, access, or privacy barriers.\n\nEvaluating storage includes considering whose access is improved or reduced by the design.` },
    { id: "ready", kicker: "Synthesize", title: "Make a storage recommendation", body: `Compare local and cloud storage through cost, speed, reliability, accessibility, privacy, and integrity. Organize files so the right person can find the right version, and separate syncing from true backup.`, checkIn: check("What makes a storage recommendation defensible?", ["It names the task, compares relevant tradeoffs, and explains why the plan fits", "It chooses the cheapest option only” belongs to a different situation than the one in the question stem", "“It ignores recovery” describes a different situation than the one in the question stem", "It always selects cloud storage” belongs to a different situation than the one in the question stem"], 0, "A recommendation needs evidence about the task’s requirements and risks.") },
  ] },
  bigIdeas: ["Local and cloud storage offer different tradeoffs in **cost, speed, reliability, accessibility, privacy, and integrity**.", "**Organization** and permissions help people use the correct version.", "**Sync** mirrors changes; a **backup** is an independent recoverable copy.", "Recommend storage based on task requirements and risk."],
  keyTerms: [{ term: "Local storage", definition: "Data stored on a device you directly use or control." }, { term: "Cloud storage", definition: "Data stored on remote provider systems and accessed through an account and network." }, { term: "Data integrity", definition: "The accuracy, completeness, and usability of data over time." }, { term: "Sync", definition: "A process that keeps copies or views matched, including many changes and deletions." }, { term: "Backup", definition: "A separate recoverable copy used after loss, deletion, or corruption." }, { term: "Permission", definition: "A rule defining whether someone can view, comment on, or edit data." }],
  realWorld: "A scholarship packet needs more than a place to save: it needs a correct format, controlled access, recovery from mistakes, and a plan for a deadline.",
  quiz: [
    { id: "q1", question: "Which tradeoff most favors local storage for editing a large video while traveling?", choices: [
            "Offline availability and fast device access",
            "Unlimited sharing” belongs to a different situation than the one in the question stem",
            "Automatic group editing” belongs to a different situation than the one in the question stem",
            "No device-failure risk” belongs to a different situation than the one in the question stem",
          ], correctIndex: 0, explanation: "Local storage can remain accessible without a connection and may handle large files quickly." },
    { id: "q2", question: "Which tradeoff most favors cloud storage for a group project?", choices: [
            "No need for account security” belongs to a different situation than the one in the question stem",
            "Authorized collaborators can access a current shared version from multiple devices",
            "No dependency on service availability” belongs to a different situation than the one in the question stem",
            "“Guaranteed free storage” describes a different situation than the one in the question stem",
          ], correctIndex: 1, explanation: "Cloud storage can improve shared access, but it still needs permissions and connectivity." },
    { id: "q3", question: "Why is sync not enough as the only backup?", choices: [
            "It cannot store documents” belongs to a different situation than the one in the question stem",
            "A deletion or corruption can propagate across synced copies",
            "It only works on phones” belongs to a different situation than the one in the question stem",
            "It is always slower” belongs to a different situation than the one in the question stem",
          ], correctIndex: 1, explanation: "Mirroring changes is useful but differs from preserving an independent recovery copy." },
    { id: "q4", question: "A portal requires a PDF. What protects data integrity?", choices: [
            "Upload the first file found” belongs to a different situation than the one in the question stem",
            "Export a real PDF and open it to verify the result",
            "Rename .docx to .pdf” belongs to a different situation than the one in the question stem",
            "Change the folder color” belongs to a different situation than the one in the question stem",
          ], correctIndex: 1, explanation: "Exporting creates the required format; renaming only changes the label." },
    { id: "q5", question: "Which access setting is appropriate for a résumé with personal contact details?", choices: [
            "Post in a public class channel",
            "Only needed reviewers can view or comment",
            "Public comment access” belongs to a different situation than the one in the question stem",
            "Anyone with link can edit” belongs to a different situation than the one in the question stem",
          ], correctIndex: 1, explanation: "Least-privilege sharing reduces unnecessary privacy and integrity risk." },
    { id: "q6", question: "What makes a storage plan strong?", choices: [
            "It stores every file in Downloads” belongs to a different situation than the one in the question stem",
            "It matches access, speed, privacy, reliability, cost, and recovery needs to the task",
            "“It uses the newest service” describes a different situation than the one in the question stem",
            "“It relies on one copy” describes a different situation than the one in the question stem",
          ], correctIndex: 1, explanation: "A sound plan is an evidence-based response to the actual task." },
  ],
  reflection: { prompt: "Choose a real school, scholarship, internship, or group-project file. Recommend where and how it should be stored, using at least three tradeoff criteria and a recovery plan.", placeholder: "My group’s slides should use a restricted shared folder for access and version history, plus an exported backup before the deadline…" },
};
