import type { LucideIcon } from "lucide-react";
import {
  Archive,
  Binary,
  BookOpenCheck,
  Bot,
  Brain,
  Briefcase,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChartScatter,
  Compass,
  Copyright,
  Cpu,
  Ear,
  Eye,
  FileStack,
  Filter,
  Fingerprint,
  Flame,
  FolderTree,
  Gauge,
  GitBranch,
  Globe2,
  GraduationCap,
  Handshake,
  HeartPulse,
  KeyRound,
  Landmark,
  Layers,
  Library,
  Link2,
  ListChecks,
  Lock,
  MessageSquareText,
  Microscope,
  Monitor,
  PenTool,
  Radar,
  RefreshCw,
  Scale,
  ScanSearch,
  Search,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Speech,
  Table2,
  Target,
  Trophy,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";

/** Lucide icon for each lesson badge — unique, track-fitting, no emoji. */
export const LESSON_BADGE_ICONS: Record<string, LucideIcon> = {
  // AI + Python
  "lesson-1": Bot,
  "lesson-2": Ear,
  "lesson-3": GitBranch,
  "lesson-4": ListChecks,
  "lesson-5": RefreshCw,
  "lesson-6": ScanSearch,
  "lesson-7": Eye,
  "lesson-8": Archive,
  "lesson-9": FolderTree,
  "lesson-10": Layers,
  "lesson-11": SlidersHorizontal,
  "lesson-12": Shield,
  "lesson-13": PenTool,
  "lesson-14": Compass,

  // Data Analyst
  "da-1": Table2,
  "da-2": Search,
  "da-3": Library,
  "da-4": Filter,
  "da-5": Trophy,
  "da-6": Gauge,
  "da-7": Link2,
  "da-8": MessageSquareText,
  "da-9": ChartColumn,
  "da-10": ChartPie,
  "da-11": ChartLine,
  "da-12": ChartScatter,
  "da-13": Microscope,
  "da-14": Flame,

  // AI Literacy
  "ai-1": Brain,
  "ai-2": Radar,
  "ai-3": Cpu,
  "ai-4": Binary,
  "ai-5": Sparkles,
  "ai-6": Target,
  "ai-7": PenTool,
  "ai-8": MessageSquareText,
  "ai-9": KeyRound,
  "ai-10": Speech,
  "ai-11": ScanSearch,
  "ai-12": BookOpenCheck,
  "ai-13": Scale,
  "ai-14": Fingerprint,
  "ai-15": Briefcase,
  "ai-16": ShieldCheck,

  // Digital Literacy
  "dl-1": Monitor,
  "dl-2": FileStack,
  "dl-3": Search,
  "dl-4": Eye,
  "dl-5": Speech,
  "dl-6": Handshake,
  "dl-7": Globe2,
  "dl-8": Users,
  "dl-9": PenTool,
  "dl-10": Copyright,
  "dl-11": Lock,
  "dl-12": ShieldCheck,
  "dl-13": HeartPulse,
  "dl-14": Wrench,
  "dl-15": Briefcase,
  "dl-16": Compass,

  // Cybersecurity
  "cs-1": Shield,
  "cs-2": ShieldCheck,
  "cs-3": Radar,
  "cs-4": Eye,
  "cs-5": KeyRound,
  "cs-6": Lock,
  "cs-7": Globe2,
  "cs-8": Layers,
  "cs-9": Binary,
  "cs-10": Fingerprint,
  "cs-11": Wrench,
  "cs-12": Flame,
  "cs-13": Target,
  "cs-14": ScanSearch,
  "cs-15": Scale,
  "cs-16": Trophy,

  // Financial Literacy
  "fl-1": Wallet,
  "fl-2": Scale,
  "fl-3": Briefcase,
  "fl-4": Landmark,
  "fl-5": ListChecks,
  "fl-6": Gauge,
  "fl-7": ChartLine,
  "fl-8": ShieldCheck,
  "fl-9": Sparkles,
  "fl-10": ChartPie,
  "fl-11": Shield,
  "fl-12": Eye,
  "fl-13": FileStack,
  "fl-14": GraduationCap,
  "fl-15": Target,
  "fl-16": Trophy,
};

/** Fallback when a lesson id is unknown. */
export const DEFAULT_BADGE_ICON: LucideIcon = Trophy;

export function badgeIconForLesson(lessonId: string): LucideIcon {
  return LESSON_BADGE_ICONS[lessonId] ?? DEFAULT_BADGE_ICON;
}

/**
 * Resolve a lesson id from a free-form badge label (lesson canvases store name only).
 * Prefer passing lessonId when available.
 */
export function lessonIdFromBadgeLabel(badge: string): string | null {
  const name = badge.replace(/^[^\w]+/, "").trim().toLowerCase();
  const entries: Array<[string, string]> = [
    ["the awakener", "lesson-1"],
    ["listener", "lesson-2"],
    ["decision maker", "lesson-3"],
    ["rule builder", "lesson-4"],
    ["loop starter", "lesson-5"],
    ["pattern finder", "lesson-6"],
    ["pattern spotter", "lesson-7"],
    ["memory builder", "lesson-8"],
    ["memory organizer", "lesson-9"],
    ["skill builder", "lesson-10"],
    ["parameter pro", "lesson-11"],
    ["rule guide", "lesson-12"],
    ["designer", "lesson-13"],
    ["quest builder", "lesson-14"],
    ["data spotter", "da-1"],
    ["query starter", "da-2"],
    ["column picker", "da-3"],
    ["filter finder", "da-4"],
    ["rank master", "da-5"],
    ["summary pro", "da-6"],
    ["table joiner", "da-7"],
    ["question asker", "da-8"],
    ["chart maker", "da-9"],
    ["slice master", "da-10"],
    ["trend spotter", "da-11"],
    ["distribution detective", "da-12"],
    ["relationship finder", "da-13"],
    ["data analyst", "da-14"],
    ["ai explorer", "ai-1"],
    ["ai spotter", "ai-2"],
    ["sense maker", "ai-3"],
    ["data translator", "ai-4"],
    ["pattern learner", "ai-5"],
    ["model tester", "ai-6"],
    ["creator's apprentice", "ai-7"],
    ["llm insider", "ai-8"],
    ["prompt starter", "ai-9"],
    ["prompt pro", "ai-10"],
    ["fact checker", "ai-11"],
    ["honest scholar", "ai-12"],
    ["fairness guardian", "ai-13"],
    ["privacy defender", "ai-14"],
    ["future ready", "ai-15"],
    ["ai-smart citizen", "ai-16"],
    ["tech foundations", "dl-1"],
    ["file wrangler", "dl-2"],
    ["search sleuth", "dl-3"],
    ["truth seeker", "dl-4"],
    ["clear communicator", "dl-5"],
    ["team player", "dl-6"],
    ["footprint keeper", "dl-7"],
    ["digital citizen", "dl-8"],
    ["content creator", "dl-9"],
    ["credit giver", "dl-10"],
    ["security guard", "dl-11"],
    ["privacy protector", "dl-12"],
    ["balance keeper", "dl-13"],
    ["problem solver", "dl-14"],
    ["career ready", "dl-15"],
    ["digitally fluent", "dl-16"],
    ["cyber rookie", "cs-1"],
    ["triad guardian", "cs-2"],
    ["threat spotter", "cs-3"],
    ["phish defender", "cs-4"],
    ["credential pro", "cs-5"],
    ["gatekeeper", "cs-6"],
    ["net scout", "cs-7"],
    ["firewall builder", "cs-8"],
    ["cipher starter", "cs-9"],
    ["trust verifier", "cs-10"],
    ["hardener", "cs-11"],
    ["incident ready", "cs-12"],
    ["attack analyst", "cs-13"],
    ["privacy scout", "cs-14"],
    ["risk analyst", "cs-15"],
    ["cyber defender", "cs-16"],
    ["money starter", "fl-1"],
    ["tradeoff thinker", "fl-2"],
    ["paycheck pro", "fl-3"],
    ["banking basics", "fl-4"],
    ["budget builder", "fl-5"],
    ["cash flow keeper", "fl-6"],
    ["credit reader", "fl-7"],
    ["debt defender", "fl-8"],
    ["growth saver", "fl-9"],
    ["investor apprentice", "fl-10"],
    ["coverage checker", "fl-11"],
    ["consumer guardian", "fl-12"],
    ["tax rookie", "fl-13"],
    ["aid navigator", "fl-14"],
    ["decision pro", "fl-15"],
    ["money planner", "fl-16"],
  ];
  for (const [label, id] of entries) {
    if (name === label || name.endsWith(label)) return id;
  }
  return null;
}
