import type { AILessonConfig } from "@/components/ai/AILessonCanvas";

const check = (prompt: string, choices: string[], correctIndex: number, explanation: string) => ({
  prompt, choices, correctIndex, explanation,
});

export const advancedAiLesson1: AILessonConfig = {
  id: "aai-1",
  title: "1. AI Systems: Framing Problems Worth Solving",
  goal: "Turn a vague AI idea into a bounded decision, success criterion, and non-AI alternative.",
  xpReward: 50,
  badge: "Problem Framer",
  dashboardHref: "/dashboard",
  nextHref: "/learn/advanced-ai/2",
  lessonModule: {
    durationLabel: "~40–50 min lesson",
    sections: [
      { id: "brief", kicker: "Roadmap", title: "From “use AI” to a decision contract", body: `A project begins with a decision, not a model. For a scholarship application helper: **input** is the submitted form, **output** is \`complete | needs-review\`, and **action** is a counselor review—not automatic rejection.

A useful contract names the user, allowed inputs, decision owner, error cost, and a measurable success threshold.

**Instructor lens — make the contract observable.** Put the claim on the board, then ask students to identify the moment at which a person, not software, remains accountable. Walk through one representative case using actual values: an applicant uploads 4 of 5 required items; the checker reports “likely missing transcript”; a counselor verifies the record and chooses the outreach. The score is evidence, while the follow-up rule is policy. Students often merge those two roles and say “the AI decided.” Correct that language: the system surfaced a signal; the institution chose an action.

**Why this matters:** a model can be statistically useful and still be unsafe when its output silently expands into a decision about eligibility, opportunity, or discipline. In the lab, add one normal case, one messy-but-valid case, and one case outside the stated authority. For each, write the allowed action, the owner, and the recovery message. Keep a one-line record of the harm that the design is trying to prevent.`, image: "/images/lessons/aai-1.png", imageAlt: "Students and an instructor planning an Advanced AI 1 project around a whiteboard." },
      { id: "boundary", kicker: "Frame", title: "Separate prediction from policy", body: `A model can estimate “missing document likely”; policy decides whether a student is contacted, delayed, or denied. Keeping those layers separate makes decisions explainable and changeable.

| Layer | Scholarship helper example |
| --- | --- |
| Prediction | Is a required attachment absent? |
| Policy | Notify applicant and queue counselor review |
| Accountability | Counselor owns final eligibility decision |

**Worked design review.** Have pairs turn the slide’s idea into a small table with three columns: “known at decision time,” “system may recommend,” and “human or rule must decide.” For example, an upload timestamp and a required-file list are known at intake; “needs a document check” is a permissible recommendation; eligibility remains a counselor decision. Challenge the tempting shortcut: a polished explanation or a high score does not create authority. Ask what changes if the score is wrong for 10 of 100 students, and require students to name who absorbs the delay or extra work.

**Lab move:** test the non-AI baseline first. Run the same ten cases through a checklist, a simple search rule, or a human workflow and record time, misses, and recovery quality. If that baseline already meets the harm-tied goal, an AI component has not earned its complexity. Save the rejected cases; they are more valuable than a dashboard average because they reveal where the boundary needs to be tightened.`, checkIn: check("Which statement is a policy action rather than a model prediction?", ["The model estimates a missing file with probability near 0.82","Staff send a reminder when a required file looks missing","The uploaded form contains twelve labeled input fields today","The essay file name looks unusual compared with other uploads"], 1, "Policy specifies the human/system action taken after a signal.") },
      { id: "stakeholders", kicker: "People first", title: "Map who bears each error", body: `A false “complete” result delays a student; a false “incomplete” result creates avoidable work. Ask the applicant, counselor, IT owner, and accessibility coordinator what a bad result costs. Their answers shape the threshold and appeal route.

**Misconception to interrupt:** “more automation” is not automatically better engineering. A narrow assistant is successful when it knows what it is not allowed to decide and hands off uncertain cases predictably. Model a scope-fence review aloud: Does the input belong to the intended task? Is the proposed output merely a flag, or does it change a person’s access? Is there a named owner and a way to correct the record? If any answer is unclear, the next step is clarification or human review—not a stronger model.

**Evidence students should produce:** a decision contract, a baseline comparison, and an error log with at least three cases. Include one false alarm and one missed case in plain language, then explain the different harms. In a lab debrief, ask which harm deserves faster recovery and why. This connects a technical threshold or workflow choice to a real student experience without pretending that the model is neutral.`, checkIn: check("Why must a decision contract name an accountable owner?", ["Owners make neural networks train much faster overnight","Someone must review, correct, and defend the action taken","Owners remove the need for any evaluation metrics at all","Owners guarantee the model never produces errors in class"], 1, "Accountability stays with people and policy, not a score.") },
      { id: "non-ai", kicker: "Baseline", title: "Prove AI is needed", body: `If required files have stable names, a deterministic checklist is better than ML: it is cheap, predictable, and auditable. Use AI only for the fuzzy part, such as matching a document called \`my essay final.pdf\` to an essay requirement.

**Instructor protocol:** pause before implementation and run a “no-build” challenge. One group argues for the proposed assistant; another argues that a checklist, clearer form, staff process, or human-only path is safer. They must use the same evidence: input quality, volume, error cost, accessibility, and who can appeal. A good proposal does not win by claiming AI is accurate; it wins by showing that its bounded action improves a measurable outcome without shifting unreviewed power to software.

**In the lab:** write expected behavior for ambiguous input, unsupported input, and a user correction. Include the exact language a user sees when the system cannot verify something. Then assign an operational owner who reviews logs and can pause the feature. These details are not administrative extras: they are the mechanism that turns an attractive demo into a defensible, limited decision-support system.` },
      { id: "scope", kicker: "Mechanism", title: "Write an explicit scope fence", body: `\`\`\`text
IN SCOPE: detect likely missing required files
OUT OF SCOPE: judge essay quality, eligibility, or financial need
ESCALATE: unreadable uploads, confidence < 0.90, conflicting records
\`\`\`
A scope fence prevents a helpful feature from becoming an unreviewed decision-maker.

**Instructor lens — make the contract observable.** Put the claim on the board, then ask students to identify the moment at which a person, not software, remains accountable. Walk through one representative case using actual values: an applicant uploads 4 of 5 required items; the checker reports “likely missing transcript”; a counselor verifies the record and chooses the outreach. The score is evidence, while the follow-up rule is policy. Students often merge those two roles and say “the AI decided.” Correct that language: the system surfaced a signal; the institution chose an action.

**Why this matters:** a model can be statistically useful and still be unsafe when its output silently expands into a decision about eligibility, opportunity, or discipline. In the lab, add one normal case, one messy-but-valid case, and one case outside the stated authority. For each, write the allowed action, the owner, and the recovery message. Keep a one-line record of the harm that the design is trying to prevent.`, image: "/images/lessons/aai-1-b.png", imageAlt: "A realistic classroom lab screen showing lesson 1 notes, examples, and evidence." },
      { id: "metric", kicker: "Evidence", title: "Choose a metric tied to harm", body: `For 100 manually reviewed submissions, suppose 18 really lack a file. A practical pass criterion could be: catch at least 17 of 18 while sending no more than 12 complete submissions to review. That is more meaningful than “high accuracy.”

**Worked design review.** Have pairs turn the slide’s idea into a small table with three columns: “known at decision time,” “system may recommend,” and “human or rule must decide.” For example, an upload timestamp and a required-file list are known at intake; “needs a document check” is a permissible recommendation; eligibility remains a counselor decision. Challenge the tempting shortcut: a polished explanation or a high score does not create authority. Ask what changes if the score is wrong for 10 of 100 students, and require students to name who absorbs the delay or extra work.

**Lab move:** test the non-AI baseline first. Run the same ten cases through a checklist, a simple search rule, or a human workflow and record time, misses, and recovery quality. If that baseline already meets the harm-tied goal, an AI component has not earned its complexity. Save the rejected cases; they are more valuable than a dashboard average because they reveal where the boundary needs to be tightened.`, checkIn: check("When is a non-AI checklist the better first system?", ["Rules are stable, fields are structured, and audits matter","You already bought a large model and need somewhere to use it","Labels are messy and stakeholders disagree on every hard case","The task is to generate creative posters for a school fair day"], 0, "Clear, stable rules rarely need a learned model first.") },
      { id: "table", kicker: "Design review", title: "Compare three solution shapes", body: `| Approach | Best when | Main risk |
| --- | --- | --- |
| Checklist | Fields are structured | Misses messy filenames |
| Classifier | Labels from past reviews exist | Learns old staff habits |
| Human-only | Stakes are high or volume is low | Slow and inconsistent |

**Misconception to interrupt:** “more automation” is not automatically better engineering. A narrow assistant is successful when it knows what it is not allowed to decide and hands off uncertain cases predictably. Model a scope-fence review aloud: Does the input belong to the intended task? Is the proposed output merely a flag, or does it change a person’s access? Is there a named owner and a way to correct the record? If any answer is unclear, the next step is clarification or human review—not a stronger model.

**Evidence students should produce:** a decision contract, a baseline comparison, and an error log with at least three cases. Include one false alarm and one missed case in plain language, then explain the different harms. In a lab debrief, ask which harm deserves faster recovery and why. This connects a technical threshold or workflow choice to a real student experience without pretending that the model is neutral.` },
      { id: "lab", kicker: "Lab", title: "Turn one idea into test cases", body: `Create ten applications: normal PDFs, photographed documents, an optional file, a file with an unusual name, and a corrupted upload. For each, record expected output and the recovery path. A “happy path” is not an evaluation set.

**Instructor protocol:** pause before implementation and run a “no-build” challenge. One group argues for the proposed assistant; another argues that a checklist, clearer form, staff process, or human-only path is safer. They must use the same evidence: input quality, volume, error cost, accessibility, and who can appeal. A good proposal does not win by claiming AI is accurate; it wins by showing that its bounded action improves a measurable outcome without shifting unreviewed power to software.

**In the lab:** write expected behavior for ambiguous input, unsupported input, and a user correction. Include the exact language a user sees when the system cannot verify something. Then assign an operational owner who reviews logs and can pause the feature. These details are not administrative extras: they are the mechanism that turns an attractive demo into a defensible, limited decision-support system.`, checkIn: check("What belongs in a strong scope fence?", ["Only the marketing slogan for the AI feature","In-scope tasks, out-of-scope uses, and escalate cases","GPU brand, cloud region, and favorite IDE theme","A promise that every edge case will be fully automated"], 1, "Scope fences bound authority and define safe handoffs.") },
      { id: "failure", kicker: "Failure mode", title: "The chatbot that quietly decides eligibility", body: `A school asks a general chatbot “is this student eligible?” It invents a rule from an outdated webpage, and the email looks authoritative. The failure is not only hallucination: it is allowing an unapproved system to make a high-impact policy decision.

**Instructor lens — make the contract observable.** Put the claim on the board, then ask students to identify the moment at which a person, not software, remains accountable. Walk through one representative case using actual values: an applicant uploads 4 of 5 required items; the checker reports “likely missing transcript”; a counselor verifies the record and chooses the outreach. The score is evidence, while the follow-up rule is policy. Students often merge those two roles and say “the AI decided.” Correct that language: the system surfaced a signal; the institution chose an action.

**Why this matters:** a model can be statistically useful and still be unsafe when its output silently expands into a decision about eligibility, opportunity, or discipline. In the lab, add one normal case, one messy-but-valid case, and one case outside the stated authority. For each, write the allowed action, the owner, and the recovery message. Keep a one-line record of the harm that the design is trying to prevent.`, image: "/images/lessons/aai-confusion.png", imageAlt: "An educational lab visualization illustrating a key lesson 1 mechanism with annotated screens." },
      { id: "guardrail", kicker: "Control", title: "Design the recovery, not just output", body: `Show “We could not verify your documents; a counselor will review within two days.” Log the reason code and preserve the original upload. Do not make the student argue with a black-box score.

**Worked design review.** Have pairs turn the slide’s idea into a small table with three columns: “known at decision time,” “system may recommend,” and “human or rule must decide.” For example, an upload timestamp and a required-file list are known at intake; “needs a document check” is a permissible recommendation; eligibility remains a counselor decision. Challenge the tempting shortcut: a polished explanation or a high score does not create authority. Ask what changes if the score is wrong for 10 of 100 students, and require students to name who absorbs the delay or extra work.

**Lab move:** test the non-AI baseline first. Run the same ten cases through a checklist, a simple search rule, or a human workflow and record time, misses, and recovery quality. If that baseline already meets the harm-tied goal, an AI component has not earned its complexity. Save the rejected cases; they are more valuable than a dashboard average because they reveal where the boundary needs to be tightened.` },
      { id: "audit", kicker: "Audit", title: "Ask the no-build question", body: `Do not deploy if the input is too incomplete, the error could remove a right or opportunity, or a simpler checklist meets the goal. Saying no is an engineering decision supported by risk evidence.

**Misconception to interrupt:** “more automation” is not automatically better engineering. A narrow assistant is successful when it knows what it is not allowed to decide and hands off uncertain cases predictably. Model a scope-fence review aloud: Does the input belong to the intended task? Is the proposed output merely a flag, or does it change a person’s access? Is there a named owner and a way to correct the record? If any answer is unclear, the next step is clarification or human review—not a stronger model.

**Evidence students should produce:** a decision contract, a baseline comparison, and an error log with at least three cases. Include one false alarm and one missed case in plain language, then explain the different harms. In a lab debrief, ask which harm deserves faster recovery and why. This connects a technical threshold or workflow choice to a real student experience without pretending that the model is neutral.`, checkIn: check("Which success criterion is most useful for a document checker?", ["Catch nearly all missing files while limiting false review load","Maximize training accuracy on the easiest happy-path examples","Ship once the chatbot can write fluent apology emails, despite of","Prefer whichever model has the longest context window"], 0, "Harm-tied goals beat vague accuracy or fluency claims.") },
      { id: "artifact", kicker: "Build", title: "Produce a one-page decision brief", body: `Include: user goal, input fields, output and action, excluded uses, baseline, metric, test cases, owner, and appeal path. This brief is the artifact a teammate should be able to challenge.

**Instructor protocol:** pause before implementation and run a “no-build” challenge. One group argues for the proposed assistant; another argues that a checklist, clearer form, staff process, or human-only path is safer. They must use the same evidence: input quality, volume, error cost, accessibility, and who can appeal. A good proposal does not win by claiming AI is accurate; it wins by showing that its bounded action improves a measurable outcome without shifting unreviewed power to software.

**In the lab:** write expected behavior for ambiguous input, unsupported input, and a user correction. Include the exact language a user sees when the system cannot verify something. Then assign an operational owner who reviews logs and can pause the feature. These details are not administrative extras: they are the mechanism that turns an attractive demo into a defensible, limited decision-support system.` },
      { id: "case", kicker: "Case study", title: "A recommendation is not a ranking policy", body: `A club-event recommender can suggest three events from stated interests. It should not infer interests from disability, immigration, or disciplinary records. The recommendation is optional; students can browse the complete list.

**Instructor lens — make the contract observable.** Put the claim on the board, then ask students to identify the moment at which a person, not software, remains accountable. Walk through one representative case using actual values: an applicant uploads 4 of 5 required items; the checker reports “likely missing transcript”; a counselor verifies the record and chooses the outreach. The score is evidence, while the follow-up rule is policy. Students often merge those two roles and say “the AI decided.” Correct that language: the system surfaced a signal; the institution chose an action.

**Why this matters:** a model can be statistically useful and still be unsafe when its output silently expands into a decision about eligibility, opportunity, or discipline. In the lab, add one normal case, one messy-but-valid case, and one case outside the stated authority. For each, write the allowed action, the owner, and the recovery message. Keep a one-line record of the harm that the design is trying to prevent.`, image: "/images/lessons/aai-1-c.png", imageAlt: "Learners reviewing a worked AI system example on a monitor with notes and evidence." },
      { id: "review", kicker: "Check-in", title: "Find the missing contract field", body: `“Our AI will help students with applications.” This has no decision, input boundary, action owner, or success test. Rewrite it as a narrow claim before choosing any technology.

**Worked design review.** Have pairs turn the slide’s idea into a small table with three columns: “known at decision time,” “system may recommend,” and “human or rule must decide.” For example, an upload timestamp and a required-file list are known at intake; “needs a document check” is a permissible recommendation; eligibility remains a counselor decision. Challenge the tempting shortcut: a polished explanation or a high score does not create authority. Ask what changes if the score is wrong for 10 of 100 students, and require students to name who absorbs the delay or extra work.

**Lab move:** test the non-AI baseline first. Run the same ten cases through a checklist, a simple search rule, or a human workflow and record time, misses, and recovery quality. If that baseline already meets the harm-tied goal, an AI component has not earned its complexity. Save the rejected cases; they are more valuable than a dashboard average because they reveal where the boundary needs to be tightened.`, checkIn: check("What makes a project statement testable?", ["Naming a popular model brand in the first sentence","Naming input, output, action, and a success threshold","Promising the interface will look modern and colorful","Claiming the system will automate every school process"], 1, "A decision contract creates a falsifiable engineering claim.") },
      { id: "risk", kicker: "Tradeoff", title: "Document residual risk", body: `Even with review, students without reliable scanning tools may upload harder-to-read images and experience more delays. Record this risk, offer an alternate submission path, and measure turnaround by submission type.

**Misconception to interrupt:** “more automation” is not automatically better engineering. A narrow assistant is successful when it knows what it is not allowed to decide and hands off uncertain cases predictably. Model a scope-fence review aloud: Does the input belong to the intended task? Is the proposed output merely a flag, or does it change a person’s access? Is there a named owner and a way to correct the record? If any answer is unclear, the next step is clarification or human review—not a stronger model.

**Evidence students should produce:** a decision contract, a baseline comparison, and an error log with at least three cases. Include one false alarm and one missed case in plain language, then explain the different harms. In a lab debrief, ask which harm deserves faster recovery and why. This connects a technical threshold or workflow choice to a real student experience without pretending that the model is neutral.` },
      { id: "synthesis", kicker: "Synthesize", title: "Frame before you build", body: `Strong AI work begins by bounding authority. A model score is evidence; it is not permission to make an unstated decision.

**Instructor protocol:** pause before implementation and run a “no-build” challenge. One group argues for the proposed assistant; another argues that a checklist, clearer form, staff process, or human-only path is safer. They must use the same evidence: input quality, volume, error cost, accessibility, and who can appeal. A good proposal does not win by claiming AI is accurate; it wins by showing that its bounded action improves a measurable outcome without shifting unreviewed power to software.

**In the lab:** write expected behavior for ambiguous input, unsupported input, and a user correction. Include the exact language a user sees when the system cannot verify something. Then assign an operational owner who reviews logs and can pause the feature. These details are not administrative extras: they are the mechanism that turns an attractive demo into a defensible, limited decision-support system.` },
      { id: "ready", kicker: "Ready", title: "Exit ticket: defend the scope", body: `Name a school task that should remain human-only, and one narrow task where AI could assist. For each, state the error cost and the responsible owner.

**Instructor lens — make the contract observable.** Put the claim on the board, then ask students to identify the moment at which a person, not software, remains accountable. Walk through one representative case using actual values: an applicant uploads 4 of 5 required items; the checker reports “likely missing transcript”; a counselor verifies the record and chooses the outreach. The score is evidence, while the follow-up rule is policy. Students often merge those two roles and say “the AI decided.” Correct that language: the system surfaced a signal; the institution chose an action.

**Why this matters:** a model can be statistically useful and still be unsafe when its output silently expands into a decision about eligibility, opportunity, or discipline. In the lab, add one normal case, one messy-but-valid case, and one case outside the stated authority. For each, write the allowed action, the owner, and the recovery message. Keep a one-line record of the harm that the design is trying to prevent.`, checkIn: check("Which scope statement is strongest?", ["AI decides awards quickly so counselors can do less work","A checker flags likely absent files; counselors decide eligibility","Use AI everywhere students currently fill out paperwork, despite off","The model is always right once validation accuracy is high"], 1, "It separates assistance from the accountable decision.") }
    ],
  },
  bigIdeas: ["**Frame the decision before the model** — name input, output, action, owner, and error cost.", "Prediction is not policy: software may recommend; people remain accountable.", "A checklist can beat AI when rules are clear — prove a baseline first."],
  keyTerms: [{"term": "Decision contract", "definition": "A written claim naming user, inputs, outputs, actions, owner, error costs, and success criteria."}, {"term": "Scope fence", "definition": "Explicit in-scope, out-of-scope, and escalate cases that bound system authority."}, {"term": "Non-AI baseline", "definition": "A checklist, rule, or human workflow used to prove AI is needed."}, {"term": "Prediction vs policy", "definition": "What the system estimates versus the action an institution chooses to take."}],
  realWorld: "Scholarship offices and counselors waste trust when chatbots quietly invent eligibility rules. Strong teams ship bounded assistants with human owners.",
  quiz: [
    { id: "q1", question: "Which statement is a policy action rather than a model prediction?", choices: ["The model estimates a missing file with probability near 0.82","Staff send a reminder when a required file looks missing","The uploaded form contains twelve labeled input fields today","The essay file name looks unusual compared with other uploads"], correctIndex: 1, explanation: "Policy specifies the human/system action taken after a signal." },
    { id: "q2", question: "Why must a decision contract name an accountable owner?", choices: ["Owners make neural networks train much faster overnight","Someone must review, correct, and defend the action taken","Owners remove the need for any evaluation metrics at all","Owners guarantee the model never produces errors in class"], correctIndex: 1, explanation: "Accountability stays with people and policy, not a score." },
    { id: "q3", question: "When is a non-AI checklist the better first system?", choices: ["Rules are stable, fields are structured, and audits matter","You already bought a large model and need somewhere to use it","Labels are messy and stakeholders disagree on every hard case","The task is to generate creative posters for a school fair day"], correctIndex: 0, explanation: "Clear, stable rules rarely need a learned model first." },
    { id: "q4", question: "What belongs in a strong scope fence?", choices: ["Only the marketing slogan for the AI feature","In-scope tasks, out-of-scope uses, and escalate cases","GPU brand, cloud region, and favorite IDE theme","A promise that every edge case will be fully automated"], correctIndex: 1, explanation: "Scope fences bound authority and define safe handoffs." },
    { id: "q5", question: "Which success criterion is most useful for a document checker?", choices: ["Catch nearly all missing files while limiting false review load","Maximize training accuracy on the easiest happy-path examples","Ship once the chatbot can write fluent apology emails, despite of","Prefer whichever model has the longest context window"], correctIndex: 0, explanation: "Harm-tied goals beat vague accuracy or fluency claims." },
    { id: "q6", question: "What makes a project statement testable?", choices: ["Naming a popular model brand in the first sentence","Naming input, output, action, and a success threshold","Promising the interface will look modern and colorful","Claiming the system will automate every school process"], correctIndex: 1, explanation: "A decision contract creates a falsifiable engineering claim." },
    { id: "q7", question: "Which scope statement is strongest?", choices: ["AI decides awards quickly so counselors can do less work","A checker flags likely absent files; counselors decide eligibility","Use AI everywhere students currently fill out paperwork, despite off","The model is always right once validation accuracy is high"], correctIndex: 1, explanation: "It separates assistance from the accountable decision." }
  ],
  reflection: { prompt: "Write a one-page decision contract for a school task: user, input, output, action, owner, non-AI baseline, success criterion, and one out-of-scope use.", placeholder: "Write your answer…" },
};
