import type { AILessonConfig } from "@/components/ai/AILessonCanvas";

const check = (prompt: string, choices: string[], correctIndex: number, explanation: string) => ({
  prompt, choices, correctIndex, explanation,
});

export const advancedAiLesson7: AILessonConfig = {
  id: "aai-7",
  title: "7. Retrieval-Augmented Generation (RAG)",
  goal: "Design a grounded RAG pipeline from chunking through citation and abstention.",
  xpReward: 350,
  badge: "Retrieval Pro",
  dashboardHref: "/dashboard",
  prevHref: "/learn/advanced-ai/6",
  nextHref: "/learn/advanced-ai/8",
  instructorScript: `**Coach's note**
Today's lesson: **Retrieval-Augmented Generation (RAG)**.

**Goal:** Design a grounded RAG pipeline from chunking through citation and abstention.

**How to facilitate**
1. Warm-up: ask students what they already think about "RAG adds evidence at answer time".
2. Walk the Lesson slides — pause on check-ins; let students answer before revealing.
3. Knowledge check: circulate; ask "why?" after each quiz item, not just the letter.
4. Close: one-sentence takeaway + how this shows up in real life.

**Watch for:** guessing from hype or headlines without using the lesson vocabulary. Push students back to the definitions and examples on the slides.`,
  lessonModule: {
    durationLabel: "~40–50 min lesson",
    sections: [
      { id: "roadmap", kicker: "Roadmap", title: "RAG adds evidence at answer time", body: `Retrieval-augmented generation (RAG) retrieves relevant source chunks, then asks a model to answer from them. It improves freshness and attribution; it does not guarantee retrieval or reasoning is correct.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, image: "/images/lessons/aai-7.png", imageAlt: "Students and an instructor planning an Advanced AI 7 project around a whiteboard." },
      { id: "pipeline", kicker: "Mechanism", title: "Trace chunk → embed → retrieve → generate", body: `1. Split documents into coherent chunks. 2. Embed chunks and question into vectors. 3. Retrieve nearest permitted chunks. 4. Generate only from those chunks. 5. Check claims and citations before display.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, checkIn: check("Why chunk documents in a RAG system?", ["Chunking deletes meaning so models answer faster, despite offering ","Retrieval can return focused passages that fit the context window","Embeddings forbid storing whole files in any database","Chunking removes the need to evaluate grounding quality"], 1, "Chunks make retrieval precise and context-sized.") },
      { id: "chunk", kicker: "Design", title: "Chunk for meaning and citations", body: `A 2,000-word handbook page is too broad; a 20-word fragment loses context. Chunk by heading or paragraph, keep 100–200 token overlap where a rule crosses a boundary, and store title, date, permissions, and source URL.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, checkIn: check("Retrieved chunks are about parking; the user asked lab safety. Best behavior?", ["Answer lab safety from model memory with confident tone","Admit weak evidence, broaden retrieval, or escalate to a human","Raise temperature until the answer mentions safety equipment","Hide the retrieval list so nobody notices the mismatch while ski"], 1, "Mismatch means refuse or recover — not hallucinate.") },
      { id: "embedding", kicker: "Mechanism", title: "Vectors represent semantic neighborhoods", body: `An embedding maps text to a high-dimensional vector. “course withdrawal deadline” may be near “drop class date” even without exact word overlap. Similarity is a retrieval hint, not a guarantee that a chunk answers the question.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.` },
      { id: "worked", kicker: "Worked example", title: "Inspect a retrieval result", body: `Question: “Can I switch classes after week two?” Top chunks: (1) schedule changes, score .82; (2) athletics, .77; (3) graduation, .74. Read chunk 1: it says changes require counselor approval by day 10. Cite it; do not combine unrelated chunks into a new rule.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, image: "/images/lessons/aai-7-b.png", imageAlt: "A realistic classroom lab screen showing lesson 7 notes, examples, and evidence." },
      { id: "table", kicker: "Retrieval tuning", title: "Choose a retrieval setting intentionally", body: `| Setting | Too low | Too high |
| --- | --- | --- |
| Chunk size | Missing context | Mixed unrelated rules |
| top-k | Needed evidence absent | Distracting evidence crowds context |
| Similarity threshold | Weak chunks included | Valid paraphrases excluded |

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.` },
      { id: "grounding", kicker: "Control", title: "Make every answer earn support", body: `For each answer sentence, ask: which retrieved chunk supports it? If no chunk does, remove the sentence or say the source set does not answer. Citation presence alone is insufficient when the citation does not entail the claim.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, checkIn: check("If RAG answers fail, what should you inspect first?", ["Only the foundation-model brand on the vendor homepage","Retrieved chunks, chunking, filters, and query quality","Whether the UI used a rounded button style","How many emojis appear in the system prompt"], 1, "Retrieval quality usually matters more than model brand.") },
      { id: "access", kicker: "Security", title: "Retrieve only what the user may read", body: `Apply ACL filtering before the model sees content. A student query must not retrieve counselor notes even if the text is semantically close. Log document IDs, not private content, when possible.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.` },
      { id: "failure", kicker: "Failure mode", title: "Answering past the evidence", body: `A student asks whether a late fee can be waived. Retrieved text describes fee dates but no waiver rule. The assistant invents “contact the registrar within 48 hours.” Correct RAG behavior is an abstention plus the verified contact route.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, image: "/images/lessons/aai-rag.png", imageAlt: "An educational lab visualization illustrating a key lesson 7 mechanism with annotated screens." },
      { id: "eval", kicker: "Evidence", title: "Evaluate retrieval and generation separately", body: `Retrieval recall asks whether the supporting chunk appeared in top-k. Groundedness asks whether the answer is entailed by retrieved text. Citation correctness asks whether the displayed source actually supports the claim. One overall “RAG score” hides these failures.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.` },
      { id: "code", kicker: "Build", title: "Use a grounded answer contract", body: `\`\`\`text
QUESTION: {q}
SOURCES: [{id, text}]
RULES: cite source IDs for every factual claim.
If sources do not answer, return answer=null and reason="insufficient evidence".
\`\`\`
Then programmatically verify cited IDs are among the retrieved sources.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, checkIn: check("Which RAG practice is strongest for school handbooks?", ["Skip citations because fluent answers feel trustworthy","Show sources, test grounding","Always answer even when retrieval returns unrelated passages","Never log which chunks were used for an answer"], 1, "Evidence-first design is the advanced pattern.") },
      { id: "lab", kicker: "Lab", title: "Test retrieval with near misses", body: `Build 12 questions: exact wording, paraphrases, questions answered by adjacent headings, out-of-scope questions, and two that should be denied by access policy. Record retrieved IDs before judging prose.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.` },
      { id: "freshness", kicker: "Operations", title: "Version documents and re-index", body: `A policy revised on August 1 must supersede the old chunk. Store effective dates, delete or disable stale embeddings, and test the question that changed. RAG freshness is an ingestion operation.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, image: "/images/lessons/aai-7-c.png", imageAlt: "Learners reviewing a worked AI system example on a monitor with notes and evidence." },
      { id: "check", kicker: "Check-in", title: "Find the broken stage", body: `The answer is well written and cites a retrieved chunk, but that chunk concerns parking permits rather than class changes. Retrieval relevance or grounding failed; changing style will not fix it.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, checkIn: check("Why do access controls still matter in RAG?", ["Vector search magically respects every permission system","Retrieval must not become a backdoor past document ACLs","Handbooks are never sensitive in a school setting","Embeddings encrypt text so permissions are optional"], 1, "Permissions apply to retrieved knowledge too.") },
      { id: "audit", kicker: "Audit", title: "Measure source authority", body: `A blog post and an official policy PDF should not have equal standing. Curate sources, record ownership, and display dates so learners can evaluate authority.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.` },
      { id: "synthesis", kicker: "Synthesize", title: "RAG is evidence plumbing", body: `The pipeline is only trustworthy when chunking, authorization, retrieval, generation, and grounding checks all work together.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.` },
      { id: "ready", kicker: "Ready", title: "Exit ticket: diagnose a RAG answer", body: `For an answer with a wrong citation, state whether you would inspect chunking, top-k, source authority, prompt grounding, or all four—and why.

Instructor lens: RAG is an evidence pipeline with five independently testable stages: chunk documents into coherent, addressable units; embed chunks and the question; retrieve only authorized candidates; generate an answer constrained by those candidates; then verify claims and citations before display. Chunking is not a cosmetic preprocessing step. A chunk should preserve the rule, its exceptions, and enough heading context to identify authority. Store source title, section, effective date, owner, URL, ACL, and chunk version. Overlap can preserve a sentence that crosses a boundary, but too much overlap duplicates evidence and crowds the context window.

Retrieval quality must be measured before changing a language model. For a labeled question set, identify the supporting chunk IDs and compute recall@k: did the evidence appear among the permitted retrieved results? Inspect top-k rankings for semantic near misses, stale documents, duplicate chunks, missing metadata filters, and access-control failures. A fluent unsupported answer can arise because retrieval returned the wrong passage, because correct evidence was truncated, or because generation ignored it. Model swaps do not repair an index that cannot retrieve the answer.

Use a fail-closed contract. Apply ACL filtering before content enters the prompt; a student must never receive semantically relevant counselor notes. Require every factual claim to cite a retrieved ID whose text entails it. If no permitted source supports the answer, return an explicit insufficient-evidence result plus a verified escalation route. Log question class, candidate IDs, scores, filters, final citation IDs, index version, and abstention reason. This trace lets a teacher diagnose retrieval, generation, and governance separately while keeping private text out of ordinary logs.`, checkIn: check("What does “fail closed” mean for a grounded FAQ bot?", ["Close the school website whenever anyone asks a question","Refuse or escalate instead of inventing unsupported rules","Fail the student for asking a question not in the index","Shut down the database after every successful citation, eve"], 1, "Missing evidence should not produce a confident fake policy.") }
    ],
  },
  bigIdeas: ["RAG quality is mostly retrieval quality — inspect chunks before swapping models.", "Fail closed when evidence is missing or mismatched.", "Permissions and access control apply to retrieved knowledge too."],
  keyTerms: [{"term": "RAG", "definition": "Retrieval-augmented generation: retrieve documents, then generate with them."}, {"term": "Chunking", "definition": "Splitting documents into retrievable passages that fit context."}, {"term": "Grounding", "definition": "Tying claims to retrieved evidence with citations."}, {"term": "Top-k", "definition": "How many retrieved passages to include in the prompt."}],
  realWorld: "Enterprise AI search is mostly RAG plus access control — not magic memory of every handbook.",
  quiz: [
    { id: "q1", question: "Why chunk documents in a RAG system?", choices: ["Chunking deletes meaning so models answer faster, despite offering ","Retrieval can return focused passages that fit the context window","Embeddings forbid storing whole files in any database","Chunking removes the need to evaluate grounding quality"], correctIndex: 1, explanation: "Chunks make retrieval precise and context-sized." },
    { id: "q2", question: "Retrieved chunks are about parking; the user asked lab safety. Best behavior?", choices: ["Answer lab safety from model memory with confident tone","Admit weak evidence, broaden retrieval, or escalate to a human","Raise temperature until the answer mentions safety equipment","Hide the retrieval list so nobody notices the mismatch while ski"], correctIndex: 1, explanation: "Mismatch means refuse or recover — not hallucinate." },
    { id: "q3", question: "If RAG answers fail, what should you inspect first?", choices: ["Only the foundation-model brand on the vendor homepage","Retrieved chunks, chunking, filters, and query quality","Whether the UI used a rounded button style","How many emojis appear in the system prompt"], correctIndex: 1, explanation: "Retrieval quality usually matters more than model brand." },
    { id: "q4", question: "Which RAG practice is strongest for school handbooks?", choices: ["Skip citations because fluent answers feel trustworthy","Show sources, test grounding","Always answer even when retrieval returns unrelated passages","Never log which chunks were used for an answer"], correctIndex: 1, explanation: "Evidence-first design is the advanced pattern." },
    { id: "q5", question: "Why do access controls still matter in RAG?", choices: ["Vector search magically respects every permission system","Retrieval must not become a backdoor past document ACLs","Handbooks are never sensitive in a school setting","Embeddings encrypt text so permissions are optional"], correctIndex: 1, explanation: "Permissions apply to retrieved knowledge too." },
    { id: "q6", question: "What does “fail closed” mean for a grounded FAQ bot?", choices: ["Close the school website whenever anyone asks a question","Refuse or escalate instead of inventing unsupported rules","Fail the student for asking a question not in the index","Shut down the database after every successful citation, eve"], correctIndex: 1, explanation: "Missing evidence should not produce a confident fake policy." },
    { id: "q7", question: "Which design note is wrong for RAG?", choices: ["Inspect retrieval quality before swapping foundation models","Require citations that point to retrieved passages","Treat access tags as optional metadata you can ignore","Evaluate grounding on a frozen set of handbook questions"], correctIndex: 2, explanation: "Access control is not optional for private corpora." }
  ],
  reflection: { prompt: "Outline chunking, citation, and fail-closed rules for a student handbook Q&A bot.", placeholder: "Write your answer…" },
};
