import type { AILessonConfig } from "@/components/ai/AILessonCanvas";

const check = (prompt: string, choices: string[], correctIndex: number, explanation: string) => ({
  prompt, choices, correctIndex, explanation,
});

export const advancedAiLesson2: AILessonConfig = {
  id: "aai-2",
  title: "2. Data for Machine Learning",
  goal: "Prepare trustworthy training data, detect leakage, and document what a dataset can and cannot represent.",
  xpReward: 100,
  badge: "Data Steward",
  dashboardHref: "/dashboard",
  prevHref: "/learn/advanced-ai/1",
  nextHref: "/learn/advanced-ai/3",
  lessonModule: {
    durationLabel: "~40–50 min lesson",
    sections: [
      { id: "roadmap", kicker: "Roadmap", title: "Data is recorded history, not ground truth", body: `A dataset is a measurement system: rows represent cases, columns represent observations, and labels represent a past human judgment. Before training, ask who was measured, when, and what was missing.

**Instructor lens — data is a timed measurement process.** Draw a timeline from “case arrives” to “label becomes known,” then place every proposed feature on it. A feature is usable only if it exists at the prediction moment for every future case. Work a concrete example: on Monday a support team wants to flag students needing outreach; attendance through Monday morning can be used, but a Friday resolution code cannot. That later code may look highly predictive precisely because it contains the outcome or a staff response to it.

**Lab routine:** for five rows, record the feature source, collection date, collector, transformation, and whether a student could correct it. Then create train, validation, and test partitions before experimenting. Treat the held-out set as sealed evidence. Students commonly think cleaning means deleting inconvenient rows; instead, preserve a reason code for missingness, duplicates, exclusions, and uncertain labels so that later reviewers can see what changed.`, image: "/images/lessons/aai-2.png", imageAlt: "Students and an instructor planning an Advanced AI 2 project around a whiteboard." },
      { id: "schema", kicker: "Schema", title: "Features, labels, and provenance", body: `For spam detection, \`contains_link\`, sender domain, and word counts are features; \`spam\` is the label. Provenance records where each came from, who labeled it, and the collection date. Without it, a future teammate cannot judge whether the data fits a new use.

**Worked provenance audit.** Give students 100 ticket rows: 70 from desktop users, 25 from mobile, and 5 from voice-to-text. If the deployed queue will receive 40% mobile messages, the training collection is not representative even when every cell is neatly formatted. Ask them to calculate the counts, name the missing population, and propose a collection repair. Then compare two labelers on 20 ambiguous records. A disagreement is not a nuisance to erase; it is evidence that the target rule needs examples, an “uncertain” state, or a human-review pathway.

**Why it matters:** models inherit both the coverage and the decisions recorded in their source data. In the lab, annotate a data card with purpose, population, date range, exclusions, sensitive fields, label instructions, and known gaps. A future teammate should be able to answer “what does this row mean?” without guessing from a column name.`, checkIn: check("Which feature leaks future information for a first-week support model?", ["Attendance patterns recorded during the previous school year","Whether week-one homework was submitted on time","Final exam score posted after the course ends","The published course meeting times on the schedule"], 2, "Final exams happen after the early-week decision point.") },
      { id: "leakage", kicker: "Mechanism", title: "Spot information from the future", body: `Predicting whether a student will need tutoring using \`final_course_grade\` is leakage: that grade is known only after the outcome. Use only information available at the moment the prediction would be made.

**Misconception to interrupt:** anonymized or cleaned data is automatically safe and fair. Removing a name does not remove re-identification risk when dates, locations, rare events, or a mapping table remain. Likewise, dropping a protected column does not prove that related features are harmless. Ask students to justify every field by the bounded decision, then minimize, pseudonymize where appropriate, restrict access, and set a deletion date for raw exports.

**Lab move:** build a mini shift test. Train only on longer desktop messages, then inspect a short mobile-style message with abbreviations and transcription errors. Predict in plain language how the feature distribution differs and what monitoring or additional collection would reveal the problem. Connect this to rare classes: if only 5 of 100 cases need intervention, a system can look “accurate” while missing all five, so class counts must accompany any headline score.`, checkIn: check("Why write a dataset card before training?", ["Cards make GPUs allocate memory more efficiently without ","They document purpose, provenance, exclusions, and gaps","Cards replace the need for train and test splits","They guarantee labels contain no human disagreement"], 1, "Future teammates need to know what the data can represent.") },
      { id: "split", kicker: "Evidence", title: "Split before you inspect too much", body: `Create train/validation/test partitions before feature experiments. If the same student appears in all three, the model may memorize person-specific patterns. Group by student or time when that matches deployment.

**Instructor protocol:** hold a dataset admission hearing. One team is the data steward and presents the dataset card; another asks whether its records are timely, lawful for the purpose, complete enough for the intended users, and protected from leakage. Require evidence rather than assumptions: collection dates, a split plan, label examples, duplicate checks, and a list of fields unavailable at decision time. If the evidence is weak, the correct outcome is “not ready for model training.”

**In the lab:** make cleaning reversible. Preserve original values, document each normalization rule, and count rows before and after every exclusion. Then inspect a small sample of removed rows. This prevents a quiet cleanup choice—such as dropping rural stops, non-English text, or assistive-technology requests—from becoming an invisible decision about whose cases the model will serve.` },
      { id: "quality", kicker: "Mechanism", title: "Measure label disagreement", body: `Two staff label 40 messages as urgent/not urgent and disagree on 8. Agreement is 80%, so a model cannot honestly be expected to be perfect against that ambiguous label. Investigate the eight disagreements and clarify the rubric.

**Instructor lens — data is a timed measurement process.** Draw a timeline from “case arrives” to “label becomes known,” then place every proposed feature on it. A feature is usable only if it exists at the prediction moment for every future case. Work a concrete example: on Monday a support team wants to flag students needing outreach; attendance through Monday morning can be used, but a Friday resolution code cannot. That later code may look highly predictive precisely because it contains the outcome or a staff response to it.

**Lab routine:** for five rows, record the feature source, collection date, collector, transformation, and whether a student could correct it. Then create train, validation, and test partitions before experimenting. Treat the held-out set as sealed evidence. Students commonly think cleaning means deleting inconvenient rows; instead, preserve a reason code for missingness, duplicates, exclusions, and uncertain labels so that later reviewers can see what changed.`, image: "/images/lessons/aai-2-b.png", imageAlt: "A realistic classroom lab screen showing lesson 2 notes, examples, and evidence.", checkIn: check("Two labelers disagree on 8 of 40 urgent messages. Best next step?", ["Delete all disagreements so accuracy looks perfect","Clarify the rubric and keep uncertain cases for review","Train only on the rows where both labelers already agreed","Ignore disagreement because models average it away"], 1, "Disagreement reveals ambiguous policy, not just worker error.") },
      { id: "table", kicker: "Data card", title: "Keep a compact dataset card", body: `| Field | Example |
| --- | --- |
| Population | Help-desk messages, Sept–Nov |
| Labeler | Two trained staff members |
| Exclusions | Messages with medical details |
| Known gap | Few messages in languages other than English |

**Worked provenance audit.** Give students 100 ticket rows: 70 from desktop users, 25 from mobile, and 5 from voice-to-text. If the deployed queue will receive 40% mobile messages, the training collection is not representative even when every cell is neatly formatted. Ask them to calculate the counts, name the missing population, and propose a collection repair. Then compare two labelers on 20 ambiguous records. A disagreement is not a nuisance to erase; it is evidence that the target rule needs examples, an “uncertain” state, or a human-review pathway.

**Why it matters:** models inherit both the coverage and the decisions recorded in their source data. In the lab, annotate a data card with purpose, population, date range, exclusions, sensitive fields, label instructions, and known gaps. A future teammate should be able to answer “what does this row mean?” without guessing from a column name.` },
      { id: "clean", kicker: "Lab", title: "Normalize without erasing meaning", body: `Standardize \`YES\`, \`Yes\`, and \`yes\`; remove duplicate IDs; preserve an \`original_text\` field separately. Do not blindly delete “unusual” values: an unusual assistive-technology request may be an important edge case.

**Misconception to interrupt:** anonymized or cleaned data is automatically safe and fair. Removing a name does not remove re-identification risk when dates, locations, rare events, or a mapping table remain. Likewise, dropping a protected column does not prove that related features are harmless. Ask students to justify every field by the bounded decision, then minimize, pseudonymize where appropriate, restrict access, and set a deletion date for raw exports.

**Lab move:** build a mini shift test. Train only on longer desktop messages, then inspect a short mobile-style message with abbreviations and transcription errors. Predict in plain language how the feature distribution differs and what monitoring or additional collection would reveal the problem. Connect this to rare classes: if only 5 of 100 cases need intervention, a system can look “accurate” while missing all five, so class counts must accompany any headline score.` },
      { id: "imbalance", kicker: "Evidence", title: "Count the rare class", body: `If 950 of 1,000 emails are non-spam, a model that always says non-spam is 95% accurate and catches zero spam. Report class counts and use precision/recall or a cost-aware metric.

**Instructor protocol:** hold a dataset admission hearing. One team is the data steward and presents the dataset card; another asks whether its records are timely, lawful for the purpose, complete enough for the intended users, and protected from leakage. Require evidence rather than assumptions: collection dates, a split plan, label examples, duplicate checks, and a list of fields unavailable at decision time. If the evidence is weak, the correct outcome is “not ready for model training.”

**In the lab:** make cleaning reversible. Preserve original values, document each normalization rule, and count rows before and after every exclusion. Then inspect a small sample of removed rows. This prevents a quiet cleanup choice—such as dropping rural stops, non-English text, or assistive-technology requests—from becoming an invisible decision about whose cases the model will serve.` },
      { id: "failure", kicker: "Failure mode", title: "The hidden answer key", body: `A team uses “resolved in under one hour” to predict urgent tickets. But urgent tickets are intentionally prioritized, so the feature is created by the workflow the model is supposed to improve. The model learns a circular shortcut.

**Instructor lens — data is a timed measurement process.** Draw a timeline from “case arrives” to “label becomes known,” then place every proposed feature on it. A feature is usable only if it exists at the prediction moment for every future case. Work a concrete example: on Monday a support team wants to flag students needing outreach; attendance through Monday morning can be used, but a Friday resolution code cannot. That later code may look highly predictive precisely because it contains the outcome or a staff response to it.

**Lab routine:** for five rows, record the feature source, collection date, collector, transformation, and whether a student could correct it. Then create train, validation, and test partitions before experimenting. Treat the held-out set as sealed evidence. Students commonly think cleaning means deleting inconvenient rows; instead, preserve a reason code for missingness, duplicates, exclusions, and uncertain labels so that later reviewers can see what changed.`, image: "/images/lessons/aai-confusion.png", imageAlt: "An educational lab visualization illustrating a key lesson 2 mechanism with annotated screens.", checkIn: check("Why is a 95% accurate always-not-spam model still a failure?", ["Accuracy can never be calculated on email datasets","It can miss nearly all rare spam while looking strong overall","Spam filters are illegal to evaluate with percentages","95% means the features must contain leakage, even though it ign"], 1, "Class imbalance hides missed positives behind high accuracy.") },
      { id: "privacy", kicker: "Governance", title: "Minimize before modeling", body: `Remove names, student IDs, and free-text notes if they are not needed for the task. Pseudonyms reduce exposure but are not anonymity if a mapping still exists. Set a retention date for raw exports.

**Worked provenance audit.** Give students 100 ticket rows: 70 from desktop users, 25 from mobile, and 5 from voice-to-text. If the deployed queue will receive 40% mobile messages, the training collection is not representative even when every cell is neatly formatted. Ask them to calculate the counts, name the missing population, and propose a collection repair. Then compare two labelers on 20 ambiguous records. A disagreement is not a nuisance to erase; it is evidence that the target rule needs examples, an “uncertain” state, or a human-review pathway.

**Why it matters:** models inherit both the coverage and the decisions recorded in their source data. In the lab, annotate a data card with purpose, population, date range, exclusions, sensitive fields, label instructions, and known gaps. A future teammate should be able to answer “what does this row mean?” without guessing from a column name.` },
      { id: "shift", kicker: "Audit", title: "Compare collection to deployment", body: `Training data came from desktop email; deployment includes short mobile messages and voice-to-text mistakes. That is covariate shift: the input distribution changed. Add realistic mobile examples before release.

**Misconception to interrupt:** anonymized or cleaned data is automatically safe and fair. Removing a name does not remove re-identification risk when dates, locations, rare events, or a mapping table remain. Likewise, dropping a protected column does not prove that related features are harmless. Ask students to justify every field by the bounded decision, then minimize, pseudonymize where appropriate, restrict access, and set a deletion date for raw exports.

**Lab move:** build a mini shift test. Train only on longer desktop messages, then inspect a short mobile-style message with abbreviations and transcription errors. Predict in plain language how the feature distribution differs and what monitoring or additional collection would reveal the problem. Connect this to rare classes: if only 5 of 100 cases need intervention, a system can look “accurate” while missing all five, so class counts must accompany any headline score.` },
      { id: "code", kicker: "Build", title: "Write a split that respects time", body: `\`\`\`python
train = tickets[tickets.date < "2026-10-01"]
test  = tickets[tickets.date >= "2026-10-01"]
# never fit vocabulary or normalization on test
vectorizer.fit(train.text)
\`\`\`
Time splits answer the honest question: will yesterday’s process work on next month’s data?

**Instructor protocol:** hold a dataset admission hearing. One team is the data steward and presents the dataset card; another asks whether its records are timely, lawful for the purpose, complete enough for the intended users, and protected from leakage. Require evidence rather than assumptions: collection dates, a split plan, label examples, duplicate checks, and a list of fields unavailable at decision time. If the evidence is weak, the correct outcome is “not ready for model training.”

**In the lab:** make cleaning reversible. Preserve original values, document each normalization rule, and count rows before and after every exclusion. Then inspect a small sample of removed rows. This prevents a quiet cleanup choice—such as dropping rural stops, non-English text, or assistive-technology requests—from becoming an invisible decision about whose cases the model will serve.`, checkIn: check("Why is duplicate leakage across train and test dangerous?", ["It always shrinks files until training becomes impossible","Held-out scores look better than real-world generalization","It forces recall to zero on every rare positive class, even ","It removes labels so supervised learning cannot start"], 1, "The test set must represent unseen cases.") },
      { id: "case", kicker: "Case study", title: "A missing row is a signal", body: `In a bus-delay dataset, route IDs are missing mostly for rural stops. Dropping those rows creates an urban-only model. Preserve a missingness indicator and investigate why collection differs.

**Instructor lens — data is a timed measurement process.** Draw a timeline from “case arrives” to “label becomes known,” then place every proposed feature on it. A feature is usable only if it exists at the prediction moment for every future case. Work a concrete example: on Monday a support team wants to flag students needing outreach; attendance through Monday morning can be used, but a Friday resolution code cannot. That later code may look highly predictive precisely because it contains the outcome or a staff response to it.

**Lab routine:** for five rows, record the feature source, collection date, collector, transformation, and whether a student could correct it. Then create train, validation, and test partitions before experimenting. Treat the held-out set as sealed evidence. Students commonly think cleaning means deleting inconvenient rows; instead, preserve a reason code for missingness, duplicates, exclusions, and uncertain labels so that later reviewers can see what changed.`, image: "/images/lessons/aai-2-c.png", imageAlt: "Learners reviewing a worked AI system example on a monitor with notes and evidence." },
      { id: "check", kicker: "Check-in", title: "Choose the cleanest repair", body: `A duplicate record appears once in train and once in test. Remove or group duplicates before splitting again; otherwise test performance includes a memorized answer.

**Worked provenance audit.** Give students 100 ticket rows: 70 from desktop users, 25 from mobile, and 5 from voice-to-text. If the deployed queue will receive 40% mobile messages, the training collection is not representative even when every cell is neatly formatted. Ask them to calculate the counts, name the missing population, and propose a collection repair. Then compare two labelers on 20 ambiguous records. A disagreement is not a nuisance to erase; it is evidence that the target rule needs examples, an “uncertain” state, or a human-review pathway.

**Why it matters:** models inherit both the coverage and the decisions recorded in their source data. In the lab, annotate a data card with purpose, population, date range, exclusions, sensitive fields, label instructions, and known gaps. A future teammate should be able to answer “what does this row mean?” without guessing from a column name.`, checkIn: check("What should happen before heavy feature tuning?", ["Inspect test labels until the dashboard looks impressive","Define prediction time and create protected data splits","Train the largest available model on the full dump","Delete rare cases so every class count looks balanced"], 1, "Time and split discipline prevent false confidence.") },
      { id: "audit", kicker: "Audit", title: "Data quality is a social question", body: `Ask whose behavior is absent, whose past decisions became labels, and whether the feature encodes a protected trait by proxy. Better cleaning cannot repair an unjust target definition.

**Misconception to interrupt:** anonymized or cleaned data is automatically safe and fair. Removing a name does not remove re-identification risk when dates, locations, rare events, or a mapping table remain. Likewise, dropping a protected column does not prove that related features are harmless. Ask students to justify every field by the bounded decision, then minimize, pseudonymize where appropriate, restrict access, and set a deletion date for raw exports.

**Lab move:** build a mini shift test. Train only on longer desktop messages, then inspect a short mobile-style message with abbreviations and transcription errors. Predict in plain language how the feature distribution differs and what monitoring or additional collection would reveal the problem. Connect this to rare classes: if only 5 of 100 cases need intervention, a system can look “accurate” while missing all five, so class counts must accompany any headline score.` },
      { id: "synthesis", kicker: "Synthesize", title: "Protect the test set", body: `A held-out test set is evidence, not a spare training set. Once repeatedly tuned against, it becomes part of development and needs replacement.

**Instructor protocol:** hold a dataset admission hearing. One team is the data steward and presents the dataset card; another asks whether its records are timely, lawful for the purpose, complete enough for the intended users, and protected from leakage. Require evidence rather than assumptions: collection dates, a split plan, label examples, duplicate checks, and a list of fields unavailable at decision time. If the evidence is weak, the correct outcome is “not ready for model training.”

**In the lab:** make cleaning reversible. Preserve original values, document each normalization rule, and count rows before and after every exclusion. Then inspect a small sample of removed rows. This prevents a quiet cleanup choice—such as dropping rural stops, non-English text, or assistive-technology requests—from becoming an invisible decision about whose cases the model will serve.` },
      { id: "ready", kicker: "Ready", title: "Exit ticket: write a data card", body: `For a dataset you know, name one feature, one label, one collection gap, and one likely leakage risk.

**Instructor lens — data is a timed measurement process.** Draw a timeline from “case arrives” to “label becomes known,” then place every proposed feature on it. A feature is usable only if it exists at the prediction moment for every future case. Work a concrete example: on Monday a support team wants to flag students needing outreach; attendance through Monday morning can be used, but a Friday resolution code cannot. That later code may look highly predictive precisely because it contains the outcome or a staff response to it.

**Lab routine:** for five rows, record the feature source, collection date, collector, transformation, and whether a student could correct it. Then create train, validation, and test partitions before experimenting. Treat the held-out set as sealed evidence. Students commonly think cleaning means deleting inconvenient rows; instead, preserve a reason code for missingness, duplicates, exclusions, and uncertain labels so that later reviewers can see what changed.`, checkIn: check("Which feature is most suspicious for predicting loan default at application time?", ["Applicant ZIP code from the submitted form, which often hi","Stated income entered during the application","Whether the loan later became delinquent in bank records","Employment length claimed on the application"], 2, "Post-funding delinquency is classic leakage.") }
    ],
  },
  bigIdeas: ["A dataset is recorded history — labels are past human judgments, not pure truth.", "Leakage and unprotected test sets create fake accuracy.", "Document provenance, gaps, and prediction-time features before you train."],
  keyTerms: [{"term": "Feature", "definition": "An input available at prediction time used by a model."}, {"term": "Label", "definition": "The target value a supervised model learns to predict."}, {"term": "Leakage", "definition": "Using information that would not be available when the real decision is made."}, {"term": "Dataset card", "definition": "A short record of population, labelers, exclusions, and known gaps."}, {"term": "Train/validation/test split", "definition": "Separating data used for learning, tuning, and final evaluation."}],
  realWorld: "Hiring and lending tools have failed audits when training data encoded historical inequities or leaked future outcomes.",
  quiz: [
    { id: "q1", question: "Which feature leaks future information for a first-week support model?", choices: ["Attendance patterns recorded during the previous school year","Whether week-one homework was submitted on time","Final exam score posted after the course ends","The published course meeting times on the schedule"], correctIndex: 2, explanation: "Final exams happen after the early-week decision point." },
    { id: "q2", question: "Why write a dataset card before training?", choices: ["Cards make GPUs allocate memory more efficiently without ","They document purpose, provenance, exclusions, and gaps","Cards replace the need for train and test splits","They guarantee labels contain no human disagreement"], correctIndex: 1, explanation: "Future teammates need to know what the data can represent." },
    { id: "q3", question: "Two labelers disagree on 8 of 40 urgent messages. Best next step?", choices: ["Delete all disagreements so accuracy looks perfect","Clarify the rubric and keep uncertain cases for review","Train only on the rows where both labelers already agreed","Ignore disagreement because models average it away"], correctIndex: 1, explanation: "Disagreement reveals ambiguous policy, not just worker error." },
    { id: "q4", question: "Why is a 95% accurate always-not-spam model still a failure?", choices: ["Accuracy can never be calculated on email datasets","It can miss nearly all rare spam while looking strong overall","Spam filters are illegal to evaluate with percentages","95% means the features must contain leakage, even though it ign"], correctIndex: 1, explanation: "Class imbalance hides missed positives behind high accuracy." },
    { id: "q5", question: "Why is duplicate leakage across train and test dangerous?", choices: ["It always shrinks files until training becomes impossible","Held-out scores look better than real-world generalization","It forces recall to zero on every rare positive class, even ","It removes labels so supervised learning cannot start"], correctIndex: 1, explanation: "The test set must represent unseen cases." },
    { id: "q6", question: "What should happen before heavy feature tuning?", choices: ["Inspect test labels until the dashboard looks impressive","Define prediction time and create protected data splits","Train the largest available model on the full dump","Delete rare cases so every class count looks balanced"], correctIndex: 1, explanation: "Time and split discipline prevent false confidence." },
    { id: "q7", question: "Which feature is most suspicious for predicting loan default at application time?", choices: ["Applicant ZIP code from the submitted form, which often hi","Stated income entered during the application","Whether the loan later became delinquent in bank records","Employment length claimed on the application"], correctIndex: 2, explanation: "Post-funding delinquency is classic leakage." }
  ],
  reflection: { prompt: "For a dataset you know, name one feature, one label, one collection gap, and one leakage risk. Explain how you would split the data.", placeholder: "Write your answer…" },
};
