import type { AILessonConfig } from "@/components/ai/AILessonCanvas";

const check = (prompt: string, choices: string[], correctIndex: number, explanation: string) => ({
  prompt, choices, correctIndex, explanation,
});

export const advancedAiLesson5: AILessonConfig = {
  id: "aai-5",
  title: "5. Computer Vision Pipelines",
  goal: "Build an image-classification pipeline while testing visual shift, labels, and privacy constraints.",
  xpReward: 250,
  badge: "Vision Builder",
  dashboardHref: "/dashboard",
  prevHref: "/learn/advanced-ai/4",
  nextHref: "/learn/advanced-ai/6",
  instructorScript: `**Coach's note**
Today's lesson: **Computer Vision Pipelines**.

**Goal:** Build an image-classification pipeline while testing visual shift, labels, and privacy constraints.

**How to facilitate**
1. Warm-up: ask students what they already think about "Define what the camera is allowed to decide".
2. Walk the Lesson slides — pause on check-ins; let students answer before revealing.
3. Knowledge check: circulate; ask "why?" after each quiz item, not just the letter.
4. Close: one-sentence takeaway + how this shows up in real life.

**Watch for:** guessing from hype or headlines without using the lesson vocabulary. Push students back to the definitions and examples on the slides.`,
  lessonModule: {
    durationLabel: "~40–50 min lesson",
    sections: [
      { id: "vision-contract", kicker: "Roadmap", title: "Define what the camera is allowed to decide", body: `A vision project begins by separating a visible observation from a consequential decision. A cafeteria sorter may classify an item as \`plastic\`, \`paper\`, \`compost\`, or \`uncertain\`; it should not infer who left the item, whether a student is complying, or whether a classroom deserves punishment. Write the contract before collecting photographs: identify the camera position, allowed capture times, label vocabulary, action for each prediction, human owner, and deletion date. This prevents a small object-recognition task from quietly becoming surveillance.

A useful contract also names exclusions. Faces, name tags, screens, and background conversations are not features for a bin classifier. The output is decision support such as a bin instruction, not an authoritative environmental record. If a label is uncertain, the product must say so rather than force a confident-looking class.`, image: "/images/lessons/aai-5.png", imageAlt: "Students and an instructor planning an Advanced AI 5 project around a whiteboard." },
      { id: "image-pipeline", kicker: "Mechanism", title: "Trace every transformation from lens to action", body: `An image pipeline is a chain of measurement choices: capture, crop, decode, resize, color conversion, normalization, model inference, score calibration, policy, and logging. Each stage can change what the model receives. A phone may save a rotated image; a server may center-crop away the object; a normalization routine may assume RGB while an upload is RGBA. The CNN does not see “a bottle”; it sees the final numeric tensor produced by this chain.

For a 224×224 RGB classifier, document the exact resize rule, interpolation method, pixel range, channel order, mean and standard deviation, and handling of corrupt files. Run the same transform in training and production. Then test the deployed pipeline with raw images, not only notebook tensors. A model can be correct in isolation while the product is wrong because its image preparation differs.`, checkIn: check("Why must training and production use the same image transform?", ["CNNs ignore pixel values once a logo is present, which often ","A transform change changes the numeric input the model sees","Matching transforms remove any need for class labels","Identical pipelines guarantee privacy for bystanders"], 1, "Resize, color, and normalization are part of the measurement.") },
      { id: "label-rubric", kicker: "Labels", title: "Turn visual categories into an auditable rubric", body: `Labels are policy decisions expressed as training targets. “Cardboard” sounds simple until labelers see a wet box, a pizza box with grease, a paper cup with plastic lining, or an object that occupies two bins. Create a rubric with positive examples, exclusion examples, a hierarchy for mixed objects, and an \`uncertain / needs inspection\` label. Train at least two labelers on the rubric, then sample their disagreements. Disagreement is evidence that the class boundary is unclear, not merely worker error.

| Item observed | Material fact | Operational label |
| --- | --- | --- |
| Clean cereal box | Paper fiber | Paper |
| Greasy pizza box | Cardboard fiber | Compost or contamination, per local policy |
| Bottle with liquid | Plastic + contents | Empty first; uncertain if contents are unseen |

Keep the image ID, rubric version, labeler decision, and reason code. When policy changes, relabel or version the dataset rather than mixing old and new meanings.` },
      { id: "worked-metrics", kicker: "Worked example", title: "Calculate class-specific harm before celebrating accuracy", body: `Suppose a pilot evaluates 200 tray images: 120 paper, 50 plastic, and 30 contamination. The classifier correctly identifies 112 paper, 43 plastic, and 12 contamination items. It has 167 correct predictions, or 83.5% overall accuracy. That headline conceals the important failure: contamination recall is only 12/30 = 40%. If contamination is routed into compost, a low-recall class can contaminate an entire stream even while the common classes look excellent.

Build a per-class table with support, precision, recall, and the most common confusion. Then connect each error to an action: a false plastic label may create a minor incorrect hint; a false “safe to compost” label could change the operational outcome. Test the threshold and review policy against those costs, not against a single average.`, checkIn: check("Overall accuracy is 83% but contamination recall is 40%. What should you conclude?", ["The system is ready because the average looks acceptable wit","The consequential class is unsafe despite a strong average","Contamination metrics are optional for recycling helpers","Only paper-class precision matters for release decisions"], 1, "Per-class recall exposes the failure that averages hide.") },
      { id: "cnn-intuition", kicker: "Mechanism", title: "Use CNN intuition without pretending filters are human eyes", body: `A convolutional neural network applies small learned filters across an image. Early filters can respond to local contrasts such as edges, curves, color transitions, or texture; later layers combine these local patterns into representations useful for the training labels. Weight sharing means the same filter can detect a pattern in multiple locations, and stride or pooling reduces resolution so the next layer works with broader patterns. This makes CNNs efficient for images, but it does not give them human concepts or common sense.

A CNN can learn that a bottle often has a vertical highlight and cap-like edge. It can also learn that plastic appears against a blue outdoor bin if that correlation dominates training. Translation tolerance is limited: objects that are tiny, heavily occluded, upside down, badly cropped, or captured under unfamiliar lighting can still fail. Treat visualizations of activations as hypotheses to investigate with controlled examples, never as proof of why a prediction is justified.`, image: "/images/lessons/aai-5-b.png", imageAlt: "A realistic classroom lab screen showing lesson 5 notes, examples, and evidence." },
      { id: "preprocess-lab", kicker: "Lab", title: "Build a preprocessing test bench before tuning the network", body: `Create a folder of ten raw images that intentionally stress the input pipeline: portrait orientation, low light, glare, motion blur, a transparent PNG, a corrupt file, a close crop, an object at the edge, and a photo containing an irrelevant face. For each image, save the raw file, the post-crop preview, the normalized tensor summary, predicted class, score, and expected safe behavior. This lab catches failures that aggregate accuracy cannot see.

| Test condition | Expected pipeline behavior | Unsafe behavior |
| --- | --- | --- |
| Corrupt upload | Reject with a clear retry path | Fill pixels with zeros and classify |
| Object partly visible | Return uncertain or request another photo | Invent a complete object |
| Face in background | Crop/redact or decline capture per policy | Retain full scene indefinitely |

Only after this test bench passes should you compare model architectures. Otherwise an apparent CNN improvement may merely compensate for a preprocessing defect.` },
      { id: "augmentation", kicker: "Mechanism", title: "Augment the camera physics, not the imagination", body: `Data augmentation teaches invariance by changing training images in ways that could plausibly occur at capture time. For a phone-based sorting task, modest brightness changes, compression artifacts, small rotations, blur, and off-center crops may simulate real users. Record the augmentation distribution and inspect sample outputs. If an augmentation changes the label’s meaning, it creates label noise rather than robustness: flipping a label with readable text, rotating an arrow, or cropping out a safety symbol may change the actual task.

Run an ablation: train a baseline, then add one augmentation family at a time. Measure each on a held-out set grouped by lighting and device. If brightness augmentation raises dim-light recall but reduces performance on labels distinguished by color, choose based on the operational consequence. Augmentation does not replace collecting examples from missing conditions; it is a controlled assumption about what should not matter.`, checkIn: check("Which augmentation is inappropriate when labels depend on readable text?", ["A realistic brightness change that could occur on phones","A small camera blur similar to handheld capture","A flip that reverses text and changes the label meaning","A modest compression artifact from common phone saves"], 2, "Augmentations must not change the task-relevant meaning.") },
      { id: "privacy-boundary", kicker: "Governance", title: "Design visual-data privacy into collection and retention", body: `Visual data often contains more than the object the model needs. A tray image can reveal faces, disability aids, religious clothing, location signage, screens, and routine behavior. Data minimization means choosing the smallest useful field of view, cropping on-device before upload where feasible, stripping unneeded metadata, restricting access, and setting a retention schedule. Pseudonymizing a filename is insufficient if the image itself identifies people.

Make purpose binding explicit: footage collected for building security must not be repurposed for cafeteria analytics without a separate lawful and ethical review. Give users a non-camera alternative when participation affects access. Log model telemetry as counts and error categories rather than storing every raw image. Before deployment, answer who may view samples, how a correction or deletion request works, whether minors are present, and what happens when the system cannot safely avoid capturing bystanders.` },
      { id: "shortcut-failure", kicker: "Failure mode", title: "Find shortcuts with counterfactual image pairs", body: `A classifier trained with plastic bottles photographed outdoors and paper photographed indoors may report high validation accuracy while relying on background, light, or bin color. Diagnose this with counterfactual pairs: photograph the same paper item indoors and outdoors; place equivalent objects against different backgrounds; crop the object while removing the scene. If a paper item becomes “plastic” merely because it is near a blue bin, the model has learned a shortcut rather than the intended feature.

Also examine label leakage. A sticker color, camera watermark, or folder naming convention can accidentally identify a class. Hold out sites, cameras, and collection days rather than random individual photos when deployment crosses those boundaries. The fix may be balanced collection, tighter cropping, revised labels, or a narrower task—not automatically a larger CNN. Preserve the shortcut examples as regression tests so retraining cannot silently reintroduce the same behavior.`, image: "/images/lessons/aai-vision.png", imageAlt: "An educational lab visualization illustrating a key lesson 5 mechanism with annotated screens." },
      { id: "error-gallery", kicker: "Diagnosis", title: "Run error analysis as a structured investigation", body: `An error gallery is a review tool, not a slideshow of embarrassing predictions. Sample false positives, false negatives, low-confidence correct results, and confident wrong results. Tag each case by true class, predicted class, device, location, lighting, object size, occlusion, rubric version, and whether a person appears. Review the images with a domain expert who understands the real sorting policy. Ask a causal question for every cluster: was the label ambiguous, was the object genuinely out of scope, did preprocessing remove relevant information, or did the training distribution omit the condition?

| Error cluster | Likely intervention |
| --- | --- |
| Wet paper predicted compost | Add rule and examples; perhaps expose \`uncertain\` |
| Dark images predicted plastic | Collect dim-light examples; test exposure control |
| Mixed-material items | Add multi-label or abstention workflow |

Do not use the gallery to hand-pick only cases that make the next score look better. Use it to decide what behavior the system should support and what it must decline.` },
      { id: "shift-monitoring", kicker: "Operations", title: "Monitor distribution shift before users discover it", body: `Vision models encounter shift whenever the camera, location, season, inventory, or workflow changes. A model trained on bright fall photos may face winter darkness; a new bin design may introduce a novel background; a different campus may have different packaging. Monitor input signals that do not require immediate ground-truth labels: image brightness histograms, blur rate, crop failure rate, confidence distribution, class mix, camera version, and rate of \`uncertain\` responses. A sudden change is a signal to inspect, not proof that quality changed.

Pair these with privacy-reviewed human labels from a random sample. Compare per-class recall and precision by location and condition to the release baseline. Set an owner and response rule: for example, if dim-light confidence falls by 20% or contamination recall drops below the agreed threshold, disable automatic guidance for that slice and route users to static instructions while the team investigates.`, checkIn: check("Accuracy drops after deploying at a dimmer school. First investigation?", ["Train a much larger CNN before inspecting anything else","Compare capture conditions, item mix, and per-class errors","Delete the new site’s results so the old score remains","Raise confidence thresholds without collecting new samples"], 1, "Site changes often mean distribution shift across the pipeline.") },
      { id: "confidence-policy", kicker: "Control", title: "Convert scores into safe, explainable product behavior", body: `A softmax score is a relative model output, not a guarantee that the object is correctly identified. Before exposing confidence, evaluate calibration: among images scored 0.80–0.90, approximately what fraction are actually correct? Then design a policy with more than two outcomes. For example: above a calibrated high threshold, show a bin suggestion; in a middle band, show the top two possibilities plus local guidance; below a lower threshold or for out-of-distribution signals, say that the image cannot be classified safely.

The policy must fit the stakes. A playful recycling helper can ask for another photo. A medical-image workflow requires a trained professional and separate validation, not a consumer-style confidence meter. Never turn low confidence into an instruction to guess, and never let a high score override a visible contradiction reported by the user. Log which policy branch fired so the team can evaluate whether uncertainty is helping.` },
      { id: "deployment-contract", kicker: "Build", title: "Version the image transform with the model artifact", body: `Treat preprocessing as part of the model, not as miscellaneous front-end code. Store the resize dimensions, interpolation mode, color-space conversion, normalization constants, orientation handling, crop policy, label map, threshold policy, and model checksum together in a release manifest. A production request should be traceable from raw input through a transform version and model version to a policy result. If any transform changes, rerun the relevant evaluation slices.

A practical release test sends the same fixture images through training-time preprocessing and the deployed endpoint, then compares tensors or deterministic predictions within tolerance. Include tests for malformed images and unsupported formats. This catches a common failure: the notebook uses center crop and RGB scaling while the application stretches images and sends BGR values. The model was not “mysteriously worse”; the system changed its measurement instrument.`, image: "/images/lessons/aai-5-c.png", imageAlt: "Learners reviewing a worked AI system example on a monitor with notes and evidence." },
      { id: "location-case", kicker: "Case study", title: "Treat a new site as a new evaluation slice", body: `A recycling classifier reaches 88% accuracy at School A and 63% at School B. The responsible response is not to average the score and call the system good. Compare the two sites: School B may use dimmer cafeterias, different camera hardware, bilingual signage, larger trays, and packaging absent from the original data. Build a paired evaluation set that represents both locations and annotate failures by class and condition.

Decide whether a shared model can meet the required per-site standard. If not, consider a site-specific collection effort, a narrower supported label set, a different capture interface, or no automated classification at the new location. Monitor performance after changes in procurement or layout; deployment geography is not a cosmetic attribute. It defines the input distribution and can determine whether the system’s promise still holds.`, checkIn: check("Which privacy practice fits a cafeteria sorting camera?", ["Keep raw video forever and post clips publicly for portfolios","Minimize field of view, limit retention, and restrict access","Assume faces are never personal data in a school setting","Scrape hallway cameras to enrich the recycling dataset"], 1, "Purpose limitation and minimization are core privacy controls.") },
      { id: "review-workflow", kicker: "Operations", title: "Give uncertain images a real recovery path", body: `A safe vision product needs a workflow for missing, ambiguous, and unsupported inputs. Define what the interface says, what is logged, whether a human reviews anything, and how long that review takes. “Try again” is not sufficient if the result affects access or compliance. For a sorting helper, an uncertain image can display a local materials guide, invite a clearer crop, and record an anonymous error category. For higher-stakes systems, it should create a review item with the original evidence and reason code.

Practice the workflow with a tabletop drill: a camera update suddenly turns every evening photo dark; users receive conflicting suggestions; staff need to disable the automated hint. Who notices, who pauses it, what remains available to users, and how is the issue communicated? Recovery design makes monitoring actionable. It also reveals when the task should remain human-led because a timely, fair recovery path is not feasible.` },
      { id: "audit-power", kicker: "Audit", title: "Match governance to the social power of the visual task", body: `Not all vision errors carry the same consequence. Misclassifying a recyclable object is different from identifying a person, inferring emotion, estimating behavior, or flagging rule violations. The latter categories can alter privacy, dignity, discipline, access, and safety, while visual evidence is often incomplete and context-dependent. Before building, conduct a use review: identify affected people, potential disparate impact, consent or notice requirements, alternatives, appeal path, and the authority that may act on a prediction.

A useful rule is to forbid secondary use by default. Images collected for one narrow service should not be retained for future identity, attendance, or behavior models. Test representation across relevant devices and environmental conditions, but do not treat demographic inference as a shortcut for auditing. If the application cannot explain its legitimate purpose, minimize capture, provide meaningful human review, and protect people from automated adverse action.` },
      { id: "synthesis", kicker: "Synthesize", title: "Build vision systems as measured, monitored pipelines", body: `The central lesson of computer vision is that pixels acquire meaning only through a pipeline and a policy. Strong systems define label rules, preserve preprocessing, test realistic visual conditions, inspect error clusters, protect bystanders, and monitor change after release. CNN architecture is one component in that work. A better filter cannot fix contradictory labels, a purpose violation, or a deployment site never represented in evaluation.

For your own project, create an evidence packet: a task contract, label rubric, preprocessing manifest, per-class and per-condition scorecard, error gallery, privacy decision, uncertainty workflow, and monitoring owner. The packet should let another instructor reproduce your claim and challenge its limits. That is the standard for an instructor-level vision project: not “the model recognizes images,” but “this bounded pipeline behaves acceptably under stated conditions and fails safely outside them.”` },
      { id: "exit-vision", kicker: "Ready", title: "Exit ticket: defend a vision release decision", body: `Choose a campus vision task and state the narrow observable label, excluded uses, and user action. Name three deployment conditions you will test separately, one minority or high-consequence class that needs its own metric, and one kind of visual data you will remove before storage. Finally, describe the exact behavior for a corrupt, ambiguous, or low-confidence image. A complete answer connects technical preprocessing to human consequences; it does not merely name a model.

Before calling the system ready, ask whether your validation data includes the same cameras, lighting, locations, and workflow that users will encounter. If it does not, your score is an estimate for a different world. Write the condition you are least certain about and make it the first collection or pilot experiment.`, checkIn: check("What is the best use of an error gallery in vision?", ["Hand-pick only cases that make the next demo look perfect","Cluster failures by cause and choose targeted interventions","Replace per-class metrics so averages are never reported","Prove that CNNs understand objects the way humans do, even th"], 1, "Error analysis drives data, rubric, and policy fixes.") }
    ],
  },
  bigIdeas: ["Vision is a pipeline: capture → preprocess → model → policy → monitor.", "Per-class metrics and error galleries beat overall accuracy.", "Visual data carries privacy obligations — minimize and purpose-bind collection."],
  keyTerms: [{"term": "CNN", "definition": "Convolutional neural network specialized for grid-like data such as images."}, {"term": "Preprocessing", "definition": "Resize, color, and normalize steps that must match train and production."}, {"term": "Distribution shift", "definition": "When real inputs differ from training conditions (lighting, camera, site)."}, {"term": "Error gallery", "definition": "A structured review of failure clusters used to choose interventions."}],
  realWorld: "Retail and manufacturing vision systems fail when lighting or cameras change without retraining — and hallway cameras raise privacy stakes.",
  quiz: [
    { id: "q1", question: "Why must training and production use the same image transform?", choices: ["CNNs ignore pixel values once a logo is present, which often ","A transform change changes the numeric input the model sees","Matching transforms remove any need for class labels","Identical pipelines guarantee privacy for bystanders"], correctIndex: 1, explanation: "Resize, color, and normalization are part of the measurement." },
    { id: "q2", question: "Overall accuracy is 83% but contamination recall is 40%. What should you conclude?", choices: ["The system is ready because the average looks acceptable wit","The consequential class is unsafe despite a strong average","Contamination metrics are optional for recycling helpers","Only paper-class precision matters for release decisions"], correctIndex: 1, explanation: "Per-class recall exposes the failure that averages hide." },
    { id: "q3", question: "Which augmentation is inappropriate when labels depend on readable text?", choices: ["A realistic brightness change that could occur on phones","A small camera blur similar to handheld capture","A flip that reverses text and changes the label meaning","A modest compression artifact from common phone saves"], correctIndex: 2, explanation: "Augmentations must not change the task-relevant meaning." },
    { id: "q4", question: "Accuracy drops after deploying at a dimmer school. First investigation?", choices: ["Train a much larger CNN before inspecting anything else","Compare capture conditions, item mix, and per-class errors","Delete the new site’s results so the old score remains","Raise confidence thresholds without collecting new samples"], correctIndex: 1, explanation: "Site changes often mean distribution shift across the pipeline." },
    { id: "q5", question: "Which privacy practice fits a cafeteria sorting camera?", choices: ["Keep raw video forever and post clips publicly for portfolios","Minimize field of view, limit retention, and restrict access","Assume faces are never personal data in a school setting","Scrape hallway cameras to enrich the recycling dataset"], correctIndex: 1, explanation: "Purpose limitation and minimization are core privacy controls." },
    { id: "q6", question: "What is the best use of an error gallery in vision?", choices: ["Hand-pick only cases that make the next demo look perfect","Cluster failures by cause and choose targeted interventions","Replace per-class metrics so averages are never reported","Prove that CNNs understand objects the way humans do, even th"], correctIndex: 1, explanation: "Error analysis drives data, rubric, and policy fixes." },
    { id: "q7", question: "Why can strong overall accuracy still mislead a vision release?", choices: ["Images never have labels in real school deployments, which sou","A common easy class can hide failure on a rare harmful class","CNNs cannot output scores that look like probabilities","Privacy rules forbid computing any evaluation metrics"], correctIndex: 1, explanation: "Condition- and class-specific evidence reveals hidden risk." }
  ],
  reflection: { prompt: "Propose a school vision task with three test conditions, one high-consequence class metric, and one privacy safeguard.", placeholder: "Write your answer…" },
};
