import type { AILessonConfig } from "@/components/ai/AILessonCanvas";

const check = (prompt: string, choices: string[], correctIndex: number, explanation: string) => ({
  prompt, choices, correctIndex, explanation,
});

export const advancedAiLesson6: AILessonConfig = {
  id: "aai-6",
  title: "6. Language Models Beyond Prompting",
  goal: "Engineer reliable language-model outputs with tokens, schemas, context limits, and factual evaluation.",
  xpReward: 300,
  badge: "LLM Engineer",
  dashboardHref: "/dashboard",
  prevHref: "/learn/advanced-ai/5",
  nextHref: "/learn/advanced-ai/7",
  instructorScript: `**Coach's note**
Today's lesson: **Language Models Beyond Prompting**.

**Goal:** Engineer reliable language-model outputs with tokens, schemas, context limits, and factual evaluation.

**How to facilitate**
1. Warm-up: ask students what they already think about "A language model predicts tokens".
2. Walk the Lesson slides — pause on check-ins; let students answer before revealing.
3. Knowledge check: circulate; ask "why?" after each quiz item, not just the letter.
4. Close: one-sentence takeaway + how this shows up in real life.

**Watch for:** guessing from hype or headlines without using the lesson vocabulary. Push students back to the definitions and examples on the slides.`,
  lessonModule: {
    durationLabel: "~40–50 min lesson",
    sections: [
      { id: "roadmap", kicker: "Roadmap", title: "A language model predicts tokens", body: `LLMs repeatedly estimate the next token from prior tokens and supplied context. Fluent continuation is not database lookup, reasoning proof, or policy authority.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, image: "/images/lessons/aai-6.png", imageAlt: "Students and an instructor planning an Advanced AI 6 project around a whiteboard." },
      { id: "tokens", kicker: "Mechanism", title: "Tokens shape cost and context", body: `Text is split into token pieces, not always words. A 16k-token context must hold system instructions, documents, chat history, and output. Long prompts can crowd out the exact policy passage you need.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, checkIn: check("What competes for space inside an LLM context window?", ["Only the final sentence the model is about to write","Instructions, evidence, chat history, and output tokens","The model’s full weight matrices stored on disk while ski","The school’s Wi-Fi password and printer queue length"], 1, "All supplied and generated tokens share a fixed budget.") },
      { id: "schema", kicker: "Contract", title: "Ask for a typed answer", body: `For a student-services FAQ, request JSON with \`answer\`, \`policy_quote\`, \`citation\`, and \`needs_human_review\`. A schema makes missing fields detectable; it does not make facts true.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, checkIn: check("Which evaluation artifact best catches hallucinated policy claims?", ["The vendor’s marketing page for the newest model name","A golden set scored against approved source evidence","Raising temperature until answers sound more confident","A longer greeting message in the system prompt"], 1, "Claim-level checks against sources expose unsupported answers.") },
      { id: "prompt", kicker: "Mechanism", title: "Separate instructions from evidence", body: `\`\`\`text
ROLE: policy assistant
TASK: answer only from SOURCES
IF UNSUPPORTED: set needs_human_review=true
OUTPUT: JSON schema below
SOURCES: <delimited approved text>
\`\`\`
Delimiters clarify which text is evidence; they do not make untrusted text safe.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.` },
      { id: "decoding", kicker: "Mechanism", title: "Temperature changes sampling", body: `At low temperature, the model favors likely next tokens and is more repeatable. Higher temperature samples more variety. For a policy answer, use lower variability; for brainstorming, varied candidates may be useful.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, image: "/images/lessons/aai-6-b.png", imageAlt: "A realistic classroom lab screen showing lesson 6 notes, examples, and evidence." },
      { id: "table", kicker: "Evaluation", title: "Score language output by claim", body: `| Check | Question |
| --- | --- |
| Grounding | Is each claim supported by supplied text? |
| Completeness | Did it answer every required part? |
| Style | Is it clear and respectful? |
| Abstention | Did it decline unsupported requests? |

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.` },
      { id: "example", kicker: "Worked example", title: "Catch an invented deadline", body: `Source says “forms due by the first Friday in May.” The model answers “May 1.” The sentence sounds useful but is unsupported. A claim-level grader marks the deadline wrong even if the rest is polite.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, checkIn: check("Schema validation passes but a required citation is missing. What next?", ["Show the answer because the JSON shape looked valid","Treat format validity as proof the facts are correct","Send it to the safe fallback or human review path","Increase temperature and regenerate until a citation appears"], 2, "Format checks do not replace evidence checks.") },
      { id: "context", kicker: "Lab", title: "Budget context deliberately", body: `Put the most relevant current policy near the task, remove duplicate chat turns, and summarize old conversation with provenance. Never silently summarize away a restriction such as “only seniors may apply.”

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.` },
      { id: "failure", kicker: "Failure mode", title: "Fluency becomes false authority", body: `A parent receives a confident answer about transportation eligibility. The assistant blended two programs and invented a phone number. The interface must label it as assistance and offer a verified contact.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, image: "/images/lessons/aai-confusion.png", imageAlt: "An educational lab visualization illustrating a key lesson 6 mechanism with annotated screens." },
      { id: "validation", kicker: "Control", title: "Validate after generation", body: `Parse JSON, require a citation field, verify cited text exists, reject claims without support, and route rejected answers to human review. Post-generation checks turn a prompt into a system.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.` },
      { id: "code", kicker: "Build", title: "Make failure explicit", body: `\`\`\`python
answer = llm(prompt)
if not valid_schema(answer) or not cites_source(answer):
    return {"needs_human_review": True}
\`\`\`
A safe fallback is a product feature, not a model embarrassment.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, checkIn: check("A long chat “forgets” early safety rules. Most likely cause?", ["Earlier tokens fell outside the finite context window","The model deleted the school’s cloud account overnight","Embeddings automatically make context length infinite","Temperature settings erase all system instructions"], 0, "Finite context can truncate early instructions.") },
      { id: "copyright", kicker: "Governance", title: "Respect source boundaries", body: `Do not paste student records, paywalled text, or copyrighted materials into an external model without authorization. The model provider, retention settings, and data-processing agreement matter.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.` },
      { id: "case", kicker: "Case study", title: "Evaluate paraphrase and refusal", body: `Test direct questions, misspellings, conflicting source passages, a policy not in context, and requests to ignore instructions. Good behavior includes saying “I do not have enough approved information.”

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, image: "/images/lessons/aai-6-c.png", imageAlt: "Learners reviewing a worked AI system example on a monitor with notes and evidence." },
      { id: "check", kicker: "Check-in", title: "Identify hallucination risk", body: `A model cites a real-looking handbook section that is not in the provided text. Treat it as unsupported even if it sounds plausible; verify against source IDs.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, checkIn: check("Best mitigation for factual school FAQ answers?", ["Ask once politely and trust fluent wording without checking whethe","Require retrieval or citations and verify claims against sources","Always maximize temperature for creative policy language","Disable evaluation so shipping never slows down, despite offering "], 1, "Grounding plus verification beats vibes.") },
      { id: "audit", kicker: "Audit", title: "Language is an interface, not an oracle", body: `People may over-trust polished prose, especially in a school or workplace context. Design uncertainty language, citations, and human contacts into the flow.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.` },
      { id: "synthesis", kicker: "Synthesize", title: "Prompting is interface engineering", body: `Reliable LLM use combines a precise contract, controlled context, structured output, and external evaluation.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.` },
      { id: "ready", kicker: "Ready", title: "Exit ticket: write a contract", body: `Draft four lines for an assistant: role, permitted sources, unsupported-case behavior, and output schema.

Instructor lens: treat an LLM response as a sampled continuation constrained by an interface contract, not as a verified answer. Tokenization divides text into subword pieces, so a context window is a fixed budget shared by system policy, retrieved evidence, conversation history, tool results, and the completion. Count and reserve that budget deliberately: if a 16,000-token request contains 13,500 tokens of chat history, the most relevant policy may be truncated or displaced. Put authoritative, current evidence near the task; summarize older turns with source IDs; and preserve restrictions that must not be lost in compression.

Generation is controlled decoding over token probabilities. Temperature and top-p alter how much low-probability text can enter the output; low-variance settings are appropriate for policy extraction, while creative ideation can tolerate candidate diversity. Neither setting establishes truth. Embeddings are separate vector representations used to compare semantic similarity; they help locate related material but do not prove that a passage entails a claim. Build a golden set with ordinary questions, paraphrases, conflicting evidence, missing-evidence requests, and adversarial instruction attempts. For each case, score claim support, citation validity, schema validity, abstention, and escalation—not just fluency.

Operationally, require structured output, then validate it outside the model: parse the schema, check required fields, verify cited source IDs and quoted spans, reject unsupported claims, and route failures to a named human queue. Log model/version, prompt contract, context IDs, decoding settings, validator result, and final user-visible action. This makes hallucinations diagnosable. A good assistant may answer, ask a focused question, or say it lacks approved evidence; it must never fill an evidence gap with confident prose.`, checkIn: check("What should an LLM component checklist include beyond a prompt?", ["Only the font used in the chat widget","Decoding settings, eval set, and escalation path","A rule that logs are never stored for any failure","A promise that fluency equals legal correctness"], 1, "Prompts are an interface; evaluation and escalation are engineering.") }
    ],
  },
  bigIdeas: ["LLMs sample tokens — fluency is not factuality.", "Context windows are finite budgets; design what must stay in context.", "Golden-set eval and escalation make LLM components engineering, not vibes."],
  keyTerms: [{"term": "Token", "definition": "A chunk of text the model reads or generates."}, {"term": "Context window", "definition": "Maximum tokens the model can consider at once."}, {"term": "Hallucination", "definition": "Confidently generated false or unsupported content."}, {"term": "Golden set", "definition": "A frozen suite of test inputs with expected properties for regression checks."}, {"term": "Temperature", "definition": "Decoding randomness control — not a truth dial."}],
  realWorld: "Support bots that invent policy details create legal and trust disasters — grounding and evaluation are the product.",
  quiz: [
    { id: "q1", question: "What competes for space inside an LLM context window?", choices: ["Only the final sentence the model is about to write","Instructions, evidence, chat history, and output tokens","The model’s full weight matrices stored on disk while ski","The school’s Wi-Fi password and printer queue length"], correctIndex: 1, explanation: "All supplied and generated tokens share a fixed budget." },
    { id: "q2", question: "Which evaluation artifact best catches hallucinated policy claims?", choices: ["The vendor’s marketing page for the newest model name","A golden set scored against approved source evidence","Raising temperature until answers sound more confident","A longer greeting message in the system prompt"], correctIndex: 1, explanation: "Claim-level checks against sources expose unsupported answers." },
    { id: "q3", question: "Schema validation passes but a required citation is missing. What next?", choices: ["Show the answer because the JSON shape looked valid","Treat format validity as proof the facts are correct","Send it to the safe fallback or human review path","Increase temperature and regenerate until a citation appears"], correctIndex: 2, explanation: "Format checks do not replace evidence checks." },
    { id: "q4", question: "A long chat “forgets” early safety rules. Most likely cause?", choices: ["Earlier tokens fell outside the finite context window","The model deleted the school’s cloud account overnight","Embeddings automatically make context length infinite","Temperature settings erase all system instructions"], correctIndex: 0, explanation: "Finite context can truncate early instructions." },
    { id: "q5", question: "Best mitigation for factual school FAQ answers?", choices: ["Ask once politely and trust fluent wording without checking whethe","Require retrieval or citations and verify claims against sources","Always maximize temperature for creative policy language","Disable evaluation so shipping never slows down, despite offering "], correctIndex: 1, explanation: "Grounding plus verification beats vibes." },
    { id: "q6", question: "What should an LLM component checklist include beyond a prompt?", choices: ["Only the font used in the chat widget","Decoding settings, eval set, and escalation path","A rule that logs are never stored for any failure","A promise that fluency equals legal correctness"], correctIndex: 1, explanation: "Prompts are an interface; evaluation and escalation are engineering." },
    { id: "q7", question: "Why is lower temperature often better for policy extraction?", choices: ["It makes the model download newer web pages automatically","It reduces random wording when you need stable structured answers","It guarantees citations even when no sources were provided","It removes the need for any schema validation step, even though it "], correctIndex: 1, explanation: "Lower variance suits deterministic extraction tasks." }
  ],
  reflection: { prompt: "Write three golden-set questions for a school FAQ bot and what a correct answer must include (citations, refusals, schema).", placeholder: "Write your answer…" },
};
